<div class="alert alert-block" style="border: 2px solid #1976D2;background-color:#E3F2FD;padding:5px;font-size:0.9em;">
본 자료는 저작권법 제25조 2항에 의해 보호를 받습니다. 본 자료를 외부에 공개하지 말아주세요.<br>
본 강의만 잘 정리하면, 데이터 분석과 데이터 과학(머신러닝, 인공지능) 모두 가능합니다!<br>
<mb><a href="https://school.fun-coding.org/">잔재미코딩</a> 에서 본 강의 기반 최적화된 로드맵도 확인하실 수 있습니다</b></div>

## 코로나 국가별 확진자 수 추이 분석/시각화

### 날짜별 확진자수 최종 데이터프레임 읽기 (df_confirmed)

In [9]:
import pandas as pd
df_confirmed = pd.read_csv("COVID-19-master/final_df.csv")
df_confirmed.head()

,Country_Region,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,1/28/2020,1/29/2020,1/30/2020,...,2/28/2023,3/01/2023,3/02/2023,3/03/2023,3/04/2023,3/05/2023,3/06/2023,3/07/2023,3/08/2023,3/09/2023
0,Afghanistan,0,0,0,0,0,0,0,0,0,...,209322,209340,209358,209362,209369,209390,209406,209436,209451,209451
1,Albania,0,0,0,0,0,0,0,0,0,...,334391,334408,334408,334427,334427,334427,334427,334427,334443,334457
2,Algeria,0,0,0,0,0,0,0,0,0,...,271441,271448,271463,271469,271469,271477,271477,271490,271494,271496
3,Andorra,0,0,0,0,0,0,0,0,0,...,47866,47875,47875,47875,47875,47875,47875,47875,47890,47890
4,Angola,0,0,0,0,0,0,0,0,0,...,105255,105277,105277,105277,105277,105277,105277,105277,105288,105288

In [10]:
df_confirmed.shape

(201, 1144)

### 국가명과 iso2 매칭 테이블 읽기 (country_info)
- 국기 이미지를 가져오기가 쉽지 않음 (1년에 한번씩 변경하였음)
  - 두글자의 ISO 국가 코드 기반(예: KR), 다음 이미지가 현재 가능함 (이후 또 변경시, 본 주피터 노트북에 업데이트 예정)
  - 예: https://public.flourish.studio/country-flags/svg/kr.svg

#### 이슈
  - csv 파일에서 다음 데이터값은 데이터프레임으로 읽어들일 때, 자동으로 결측치로 변환됨
    - ‘’, ‘#N/A’, ‘#N/A N/A’, ‘#NA’, ‘-1.#IND’, ‘-1.#QNAN’, ‘-NaN’, ‘-nan’, ‘1.#IND’, ‘1.#QNAN’, ‘<NA>’, ‘N/A’, ‘NA’, ‘NULL’, ‘NaN’, ‘n/a’, ‘nan’, ‘null’
    - Namibia 국가의 iso2 값이 NA 이므로 결측치 변환을 막기 위해 다음과 같은 옵션 설정 필요
      - keep_default_na=False : 위 데이터값을 자동으로 결측치로 변환하지 않고, na_values로 지정한 데이터만 결측치로 변환
      - na_values='' : 결측치로 변환할 값을 지정

In [11]:
country_info = pd.read_csv("COVID-19-master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv", encoding='utf-8-sig', keep_default_na=False, na_values='')
country_info.head()

,Unnamed: 0.1,Unnamed: 0,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,Combined_Key
0,0,0,NaN,BW,NaN,NaN,NaN,NaN,NaN,Botswana,NaN,NaN,Botswana
1,1,1,NaN,BI,NaN,NaN,NaN,NaN,NaN,Burundi,NaN,NaN,Burundi
2,2,2,NaN,SL,NaN,NaN,NaN,NaN,NaN,Sierra Leone,NaN,NaN,Sierra Leone
3,3,3,4.0,AF,AFG,4.0,NaN,NaN,NaN,Afghanistan,33.93911,67.709953,Afghanistan
4,4,4,8.0,AL,ALB,8.0,NaN,NaN,NaN,Albania,41.15330,20.168300,Albania

In [12]:
country_info[country_info['Country_Region'] == 'Namibia']

,Unnamed: 0.1,Unnamed: 0,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,Combined_Key
115,115,115,516.0,NA,NAM,516.0,NaN,NaN,NaN,Namibia,-22.9576,18.4904,Namibia

In [13]:
country_info = country_info[['iso2', 'Country_Region']]
country_info.head()

  iso2 Country_Region
0   BW       Botswana
1   BI        Burundi
2   SL   Sierra Leone
3   AF    Afghanistan
4   AL        Albania

- 중복 행 제거

In [14]:
country_info.shape

(3560, 2)

In [18]:
# 2026.02.02 업데이트
# 기존 코드
# country_info = country_info.drop_duplicates(subset='Country_Region', keep='last')
# country_info.shape
# 개선 코드: keep='last' 사용 시 일부 국가(UK, Netherlands, Denmark 등)의 iso2가 해외 영토 코드로 매칭되는 문제 발견
# 예: United Kingdom -> TC(터크스 케이커스), Netherlands -> SX(신트마르턴), Denmark -> GL(그린란드)
# keep='first'로 변경하면 대부분 본토 코드가 선택되며, US만 AS(아메리칸 사모아)로 매칭되므로 별도 수정
country_info = country_info.drop_duplicates(subset='Country_Region', keep='first')
country_info.loc[country_info['Country_Region'] == 'US', 'iso2'] = 'US'
country_info.shape

(180, 2)

### 날짜별 국가별 확진자수와 국가별 iso2 값 병합

In [19]:
doc_final_country = pd.merge(df_confirmed, country_info, how='left', on='Country_Region')
doc_final_country.head()

,Country_Region,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,1/28/2020,1/29/2020,1/30/2020,...,3/01/2023,3/02/2023,3/03/2023,3/04/2023,3/05/2023,3/06/2023,3/07/2023,3/08/2023,3/09/2023,iso2
0,Afghanistan,0,0,0,0,0,0,0,0,0,...,209340,209358,209362,209369,209390,209406,209436,209451,209451,AF
1,Albania,0,0,0,0,0,0,0,0,0,...,334408,334408,334427,334427,334427,334427,334427,334443,334457,AL
2,Algeria,0,0,0,0,0,0,0,0,0,...,271448,271463,271469,271469,271477,271477,271490,271494,271496,DZ
3,Andorra,0,0,0,0,0,0,0,0,0,...,47875,47875,47875,47875,47875,47875,47875,47890,47890,AD
4,Angola,0,0,0,0,0,0,0,0,0,...,105277,105277,105277,105277,105277,105277,105277,105288,105288,AO

In [20]:
doc_final_country.shape

(201, 1145)

#### 없는 데이터(NaN) 확인하기

In [21]:
doc_final_country.isnull().sum()

Country_Region     0
1/22/2020          0
1/23/2020          0
1/24/2020          0
1/25/2020          0
                  ..
3/06/2023          0
3/07/2023          0
3/08/2023          0
3/09/2023          0
iso2              23
Length: 1145, dtype: int64

### 특정 컬럼에 없는 데이터(NaN)가 있는 경우, 해당 행들만 보여주기
- 특정 컬럼 조건에 맞는 행들만 추출 가능
  - dataframe[dataframe[컬럼명] 조건]

In [22]:
doc_final_country[doc_final_country['iso2'].isnull()]

,Country_Region,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,1/28/2020,1/29/2020,1/30/2020,...,3/01/2023,3/02/2023,3/03/2023,3/04/2023,3/05/2023,3/06/2023,3/07/2023,3/08/2023,3/09/2023,iso2
5,Antarctica,0,0,0,0,0,0,0,0,0,...,11,11,11,11,11,11,11,11,11,NaN
39,Comoros,0,0,0,0,0,0,0,0,0,...,9001,9001,9001,9001,9001,9001,9001,9008,9008,NaN
45,Cruise Ship,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
50,Diamond Princess,0,0,0,0,0,0,0,0,0,...,712,712,712,712,712,712,712,712,712,NaN
93,Kiribati,0,0,0,0,0,0,0,0,0,...,5013,5013,5013,5013,5013,5013,5013,5014,5014,NaN
94,"Korea, North",0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,NaN
102,Lesotho,0,0,0,0,0,0,0,0,0,...,34790,34790,34790,34790,34790,34790,34790,34790,34790,NaN
108,MS Zaandam,0,0,0,0,0,0,0,0,0,...,9,9,9,9,9,9,9,9,9,NaN
114,Marshall Islands,0,0,0,0,0,0,0,0,0,...,15618,15618,15618,15618,15618,15618,15618,15649,15649,NaN
118,Micronesia,0,0,0,0,0,0,0,0,0,...,23948,23948,23948,23948,23948,23948,23948,23948,23948,NaN
126,Nauru,0,0,0,0,0,0,0,0,0,...,5247,5247,5247,5247,5247,5247,5247,5247,5247,NaN
136,Others,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,NaN
138,Palau,0,0,0,0,0,0,0,0,0,...,5989,5989,5989,5989,5989,5989,5989,5991,5991,NaN
153,Samoa,0,0,0,0,0,0,0,0,0,...,16607,16607,16607,16607,16607,16607,16607,16607,16607,NaN
155,Sao Tome and Principe,0,0,0,0,0,0,0,0,0,...,6281,6281,6281,6281,6281,6281,6281,6281,6281,NaN
164,Solomon Islands,0,0,0,0,0,0,0,0,0,...,24575,24575,24575,24575,24575,24575,24575,24575,24575,NaN
170,Summer Olympics 2020,0,0,0,0,0,0,0,0,0,...,865,865,865,865,865,865,865,865,865,NaN
176,Tajikistan,0,0,0,0,0,0,0,0,0,...,17786,17786,17786,17786,17786,17786,17786,17786,17786,NaN
181,Tonga,0,0,0,0,0,0,0,0,0,...,16807,16807,16807,16807,16807,16807,16807,16810,16810,NaN
185,Tuvalu,0,0,0,0,0,0,0,0,0,...,2805,2805,2805,2805,2805,2805,2805,2805,2805,NaN
193,Vanuatu,0,0,0,0,0,0,0,0,0,...,12014,12014,12014,12014,12014,12014,12014,12014,12014,NaN
197,Winter Olympics 2022,0,0,0,0,0,0,0,0,0,...,535,535,535,535,535,535,535,535,535,NaN
198,Yemen,0,0,0,0,0,0,0,0,0,...,11945,11945,11945,11945,11945,11945,11945,11945,11945,NaN

In [23]:
doc_final_country[doc_final_country['iso2'].isnull()]['Country_Region']

5                 Antarctica
39                   Comoros
45               Cruise Ship
50          Diamond Princess
93                  Kiribati
94              Korea, North
102                  Lesotho
108               MS Zaandam
114         Marshall Islands
118               Micronesia
126                    Nauru
136                   Others
138                    Palau
153                    Samoa
155    Sao Tome and Principe
164          Solomon Islands
170     Summer Olympics 2020
176               Tajikistan
181                    Tonga
185                   Tuvalu
193                  Vanuatu
197     Winter Olympics 2022
198                    Yemen
Name: Country_Region, dtype: object

| 번호 | 항목                    | 설명                           |
|------|-------------------------|--------------------------------|
| 5    | Antarctica              | 국가가 아닌 남극 대륙            |
| 45   | Cruise Ship             | 국가가 아닌 유람선 관련 데이터   |
| 50   | Diamond Princess        | 국가가 아닌 유람선 (유명 크루즈 선박)|
| 108  | MS Zaandam              | 국가가 아닌 유람선 (크루즈 선박)   |
| 136  | Others                  | 국가 외 기타 항목               |
| 170  | Summer Olympics 2020    | 국가가 아닌 이벤트 (올림픽 대회)  |
| 197  | Winter Olympics 2022    | 국가가 아닌 이벤트 (올림픽 대회)  |

#### 참고: 복합 조건은 
- dataframe[(조건1) & (조건2)] : 조건1과 조건2 모두 만족 (and 조건)
- dataframe[(조건1) | (조건2)] : 조건1 또는 조건2 만족 (or 조건)
- 조건에 괄호를 넣는 것이 오동작을 방지하기 위해 좋음

```
nan_rows = doc_final_country[(doc_final_country['iso2'].isnull()) & (doc_final_country['4/01/2020'] == 0)]
nan_rows.head()
```

### 특정 컬럼에 없는 데이터 삭제하기

In [24]:
doc_final_country = doc_final_country.dropna(subset=['iso2'])

In [25]:
doc_final_country[doc_final_country['iso2'].isnull()]

Empty DataFrame
Columns: [Country_Region, 1/22/2020, 1/23/2020, 1/24/2020, 1/25/2020, 1/26/2020, 1/27/2020, 1/28/2020, 1/29/2020, 1/30/2020, 1/31/2020, 2/01/2020, 2/02/2020, 2/03/2020, 2/04/2020, 2/05/2020, 2/06/2020, 2/07/2020, 2/08/2020, 2/09/2020, 2/10/2020, 2/11/2020, 2/12/2020, 2/13/2020, 2/14/2020, 2/15/2020, 2/16/2020, 2/17/2020, 2/18/2020, 2/19/2020, 2/20/2020, 2/21/2020, 2/22/2020, 2/23/2020, 2/24/2020, 2/25/2020, 2/26/2020, 2/27/2020, 2/28/2020, 2/29/2020, 3/01/2020, 3/02/2020, 3/03/2020, 3/04/2020, 3/05/2020, 3/06/2020, 3/07/2020, 3/08/2020, 3/09/2020, 3/10/2020, 3/11/2020, 3/12/2020, 3/13/2020, 3/14/2020, 3/15/2020, 3/16/2020, 3/17/2020, 3/18/2020, 3/19/2020, 3/20/2020, 3/21/2020, 3/22/2020, 3/23/2020, 3/24/2020, 3/25/2020, 3/26/2020, 3/27/2020, 3/28/2020, 3/29/2020, 3/30/2020, 3/31/2020, 4/01/2020, 4/02/2020, 4/03/2020, 4/04/2020, 4/05/2020, 4/06/2020, 4/07/2020, 4/08/2020, 4/09/2020, 4/10/2020, 4/11/2020, 4/12/2020, 4/13/2020, 4/14/2020, 4/15/2020, 4/16/2020, 4/17/2020, 4/18/2020, 4/19/2020, 4/20/2020, 4/21/2020, 4/22/2020, 4/23/2020, 4/24/2020, 4/25/2020, 4/26/2020, 4/27/2020, 4/28/2020, 4/29/2020, ...]
Index: []

[0 rows x 1145 columns]

### 국기 링크를 기존 컬럼 기반해서 만들어, 데이터프레임에 붙이기
- 국기 이미지를 가져오기가 쉽지 않음 (1년에 한번씩 변경하였음)
  - 두글자의 ISO 국가 코드 기반(예: KR), 다음 이미지가 현재 가능함 (이후 또 변경시, 본 주피터 노트북에 업데이트 예정)
  - 예: https://public.flourish.studio/country-flags/svg/kr.svg

- 국기 링크 만들기

In [26]:
iso2= 'AD'
flag_link = 'https://public.flourish.studio/country-flags/svg/' + iso2.lower() + '.svg'
flag_link

'https://public.flourish.studio/country-flags/svg/ad.svg'

#### 참고: 데이터프레임에 신규 컬럼 추가하기
- 데이터 프레임에 신규 컬럼 추가하기
  - 데이터프레임[신규컬럼] = pd.Series(data=데이터)
    - 데이터는 행에 맞게, [0, 1, 2] 와 같은 형태로 넣을 수 있음
- 기존 데이터프레임 컬럼 값을 기반으로 신규 컬럼 추가하기
  - apply() 함수를 사용

In [27]:
def create_flag_link(column):
    flag_link = 'https://public.flourish.studio/country-flags/svg/' + column.lower() + '.svg'
    print(flag_link)
    return flag_link

doc_final_country['iso2'] = doc_final_country['iso2'].apply(create_flag_link)

https://public.flourish.studio/country-flags/svg/af.svg
https://public.flourish.studio/country-flags/svg/al.svg
https://public.flourish.studio/country-flags/svg/dz.svg
https://public.flourish.studio/country-flags/svg/ad.svg
https://public.flourish.studio/country-flags/svg/ao.svg
https://public.flourish.studio/country-flags/svg/ag.svg
https://public.flourish.studio/country-flags/svg/ar.svg
https://public.flourish.studio/country-flags/svg/am.svg
https://public.flourish.studio/country-flags/svg/au.svg
https://public.flourish.studio/country-flags/svg/at.svg
https://public.flourish.studio/country-flags/svg/az.svg
https://public.flourish.studio/country-flags/svg/bs.svg
https://public.flourish.studio/country-flags/svg/bh.svg
https://public.flourish.studio/country-flags/svg/bd.svg
https://public.flourish.studio/country-flags/svg/bb.svg
https://public.flourish.studio/country-flags/svg/by.svg
https://public.flourish.studio/country-flags/svg/be.svg
https://public.flourish.studio/country-flags/svg/bz.svg
https://public.flourish.studio/country-flags/svg/bj.svg
https://public.flourish.studio/country-flags/svg/bt.svg
https://public.flourish.studio/country-flags/svg/bo.svg
https://public.flourish.studio/country-flags/svg/ba.svg
https://public.flourish.studio/country-flags/svg/bw.svg
https://public.flourish.studio/country-flags/svg/br.svg
https://public.flourish.studio/country-flags/svg/bn.svg
https://public.flourish.studio/country-flags/svg/bg.svg
https://public.flourish.studio/country-flags/svg/bf.svg
https://public.flourish.studio/country-flags/svg/mm.svg
https://public.flourish.studio/country-flags/svg/bi.svg
https://public.flourish.studio/country-flags/svg/cv.svg
https://public.flourish.studio/country-flags/svg/kh.svg
https://public.flourish.studio/country-flags/svg/cm.svg
https://public.flourish.studio/country-flags/svg/ca.svg
https://public.flourish.studio/country-flags/svg/cf.svg
https://public.flourish.studio/country-flags/svg/td.svg
https://public.flourish.studio/country-flags/svg/cl.svg
https://public.flourish.studio/country-flags/svg/cn.svg
https://public.flourish.studio/country-flags/svg/co.svg
https://public.flourish.studio/country-flags/svg/cg.svg
https://public.flourish.studio/country-flags/svg/cd.svg
https://public.flourish.studio/country-flags/svg/cr.svg
https://public.flourish.studio/country-flags/svg/ci.svg
https://public.flourish.studio/country-flags/svg/hr.svg
https://public.flourish.studio/country-flags/svg/cu.svg
https://public.flourish.studio/country-flags/svg/cy.svg
https://public.flourish.studio/country-flags/svg/cz.svg
https://public.flourish.studio/country-flags/svg/dk.svg
https://public.flourish.studio/country-flags/svg/dj.svg
https://public.flourish.studio/country-flags/svg/dm.svg
https://public.flourish.studio/country-flags/svg/do.svg
https://public.flourish.studio/country-flags/svg/ec.svg
https://public.flourish.studio/country-flags/svg/eg.svg
https://public.flourish.studio/country-flags/svg/sv.svg
https://public.flourish.studio/country-flags/svg/gq.svg
https://public.flourish.studio/country-flags/svg/er.svg
https://public.flourish.studio/country-flags/svg/ee.svg
https://public.flourish.studio/country-flags/svg/sz.svg
https://public.flourish.studio/country-flags/svg/et.svg
https://public.flourish.studio/country-flags/svg/fj.svg
https://public.flourish.studio/country-flags/svg/fi.svg
https://public.flourish.studio/country-flags/svg/fr.svg
https://public.flourish.studio/country-flags/svg/ga.svg
https://public.flourish.studio/country-flags/svg/gm.svg
https://public.flourish.studio/country-flags/svg/ge.svg
https://public.flourish.studio/country-flags/svg/de.svg
https://public.flourish.studio/country-flags/svg/gh.svg
https://public.flourish.studio/country-flags/svg/gr.svg
https://public.flourish.studio/country-flags/svg/gd.svg
https://public.flourish.studio/country-flags/svg/gt.svg
https://public.flourish.studio/country-flags/svg/gn.svg
https://public.flourish.studio/country-flags/svg/gw.svg
https://public.flourish.studio/country-flags/svg/gy.svg
https://public.flourish.studio/country-flags/svg/ht.svg
https://public.flourish.studio/country-flags/svg/va.svg
https://public.flourish.studio/country-flags/svg/hn.svg
https://public.flourish.studio/country-flags/svg/hu.svg
https://public.flourish.studio/country-flags/svg/is.svg
https://public.flourish.studio/country-flags/svg/in.svg
https://public.flourish.studio/country-flags/svg/id.svg
https://public.flourish.studio/country-flags/svg/ir.svg
https://public.flourish.studio/country-flags/svg/iq.svg
https://public.flourish.studio/country-flags/svg/ie.svg
https://public.flourish.studio/country-flags/svg/il.svg
https://public.flourish.studio/country-flags/svg/it.svg
https://public.flourish.studio/country-flags/svg/jm.svg
https://public.flourish.studio/country-flags/svg/jp.svg
https://public.flourish.studio/country-flags/svg/jo.svg
https://public.flourish.studio/country-flags/svg/kz.svg
https://public.flourish.studio/country-flags/svg/ke.svg
https://public.flourish.studio/country-flags/svg/kr.svg
https://public.flourish.studio/country-flags/svg/xk.svg
https://public.flourish.studio/country-flags/svg/kw.svg
https://public.flourish.studio/country-flags/svg/kg.svg
https://public.flourish.studio/country-flags/svg/la.svg
https://public.flourish.studio/country-flags/svg/lv.svg
https://public.flourish.studio/country-flags/svg/lb.svg
https://public.flourish.studio/country-flags/svg/lr.svg
https://public.flourish.studio/country-flags/svg/ly.svg
https://public.flourish.studio/country-flags/svg/li.svg
https://public.flourish.studio/country-flags/svg/lt.svg
https://public.flourish.studio/country-flags/svg/lu.svg
https://public.flourish.studio/country-flags/svg/mg.svg
https://public.flourish.studio/country-flags/svg/my.svg
https://public.flourish.studio/country-flags/svg/mv.svg
https://public.flourish.studio/country-flags/svg/ml.svg
https://public.flourish.studio/country-flags/svg/mt.svg
https://public.flourish.studio/country-flags/svg/mr.svg
https://public.flourish.studio/country-flags/svg/mu.svg
https://public.flourish.studio/country-flags/svg/mx.svg
https://public.flourish.studio/country-flags/svg/md.svg
https://public.flourish.studio/country-flags/svg/mc.svg
https://public.flourish.studio/country-flags/svg/mn.svg
https://public.flourish.studio/country-flags/svg/me.svg
https://public.flourish.studio/country-flags/svg/ma.svg
https://public.flourish.studio/country-flags/svg/mz.svg
https://public.flourish.studio/country-flags/svg/na.svg
https://public.flourish.studio/country-flags/svg/np.svg
https://public.flourish.studio/country-flags/svg/nl.svg
https://public.flourish.studio/country-flags/svg/nz.svg
https://public.flourish.studio/country-flags/svg/ni.svg
https://public.flourish.studio/country-flags/svg/ne.svg
https://public.flourish.studio/country-flags/svg/ng.svg
https://public.flourish.studio/country-flags/svg/mk.svg
https://public.flourish.studio/country-flags/svg/no.svg
https://public.flourish.studio/country-flags/svg/om.svg
https://public.flourish.studio/country-flags/svg/pk.svg
https://public.flourish.studio/country-flags/svg/pa.svg
https://public.flourish.studio/country-flags/svg/pg.svg
https://public.flourish.studio/country-flags/svg/py.svg
https://public.flourish.studio/country-flags/svg/pe.svg
https://public.flourish.studio/country-flags/svg/ph.svg
https://public.flourish.studio/country-flags/svg/pl.svg
https://public.flourish.studio/country-flags/svg/pt.svg
https://public.flourish.studio/country-flags/svg/qa.svg
https://public.flourish.studio/country-flags/svg/ro.svg
https://public.flourish.studio/country-flags/svg/ru.svg
https://public.flourish.studio/country-flags/svg/rw.svg
https://public.flourish.studio/country-flags/svg/kn.svg
https://public.flourish.studio/country-flags/svg/lc.svg
https://public.flourish.studio/country-flags/svg/vc.svg
https://public.flourish.studio/country-flags/svg/sm.svg
https://public.flourish.studio/country-flags/svg/sa.svg
https://public.flourish.studio/country-flags/svg/sn.svg
https://public.flourish.studio/country-flags/svg/rs.svg
https://public.flourish.studio/country-flags/svg/sc.svg
https://public.flourish.studio/country-flags/svg/sl.svg
https://public.flourish.studio/country-flags/svg/sg.svg
https://public.flourish.studio/country-flags/svg/sk.svg
https://public.flourish.studio/country-flags/svg/si.svg
https://public.flourish.studio/country-flags/svg/so.svg
https://public.flourish.studio/country-flags/svg/za.svg
https://public.flourish.studio/country-flags/svg/es.svg
https://public.flourish.studio/country-flags/svg/lk.svg
https://public.flourish.studio/country-flags/svg/sd.svg
https://public.flourish.studio/country-flags/svg/sr.svg
https://public.flourish.studio/country-flags/svg/se.svg
https://public.flourish.studio/country-flags/svg/ch.svg
https://public.flourish.studio/country-flags/svg/sy.svg
https://public.flourish.studio/country-flags/svg/tw.svg
https://public.flourish.studio/country-flags/svg/tz.svg
https://public.flourish.studio/country-flags/svg/th.svg
https://public.flourish.studio/country-flags/svg/tl.svg
https://public.flourish.studio/country-flags/svg/tg.svg
https://public.flourish.studio/country-flags/svg/tt.svg
https://public.flourish.studio/country-flags/svg/tn.svg
https://public.flourish.studio/country-flags/svg/tr.svg
https://public.flourish.studio/country-flags/svg/us.svg
https://public.flourish.studio/country-flags/svg/ug.svg
https://public.flourish.studio/country-flags/svg/ua.svg
https://public.flourish.studio/country-flags/svg/ae.svg
https://public.flourish.studio/country-flags/svg/gb.svg
https://public.flourish.studio/country-flags/svg/uy.svg
https://public.flourish.studio/country-flags/svg/uz.svg
https://public.flourish.studio/country-flags/svg/ve.svg
https://public.flourish.studio/country-flags/svg/vn.svg
https://public.flourish.studio/country-flags/svg/ps.svg
https://public.flourish.studio/country-flags/svg/zm.svg
https://public.flourish.studio/country-flags/svg/zw.svg

### 데이터프레임 컬럼 조정하기

In [28]:
doc_final_country.head()

,Country_Region,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,1/28/2020,1/29/2020,1/30/2020,...,3/01/2023,3/02/2023,3/03/2023,3/04/2023,3/05/2023,3/06/2023,3/07/2023,3/08/2023,3/09/2023,iso2
0,Afghanistan,0,0,0,0,0,0,0,0,0,...,209340,209358,209362,209369,209390,209406,209436,209451,209451,https://public.flourish.studio/country-flags/s...
1,Albania,0,0,0,0,0,0,0,0,0,...,334408,334408,334427,334427,334427,334427,334427,334443,334457,https://public.flourish.studio/country-flags/s...
2,Algeria,0,0,0,0,0,0,0,0,0,...,271448,271463,271469,271469,271477,271477,271490,271494,271496,https://public.flourish.studio/country-flags/s...
3,Andorra,0,0,0,0,0,0,0,0,0,...,47875,47875,47875,47875,47875,47875,47875,47890,47890,https://public.flourish.studio/country-flags/s...
4,Angola,0,0,0,0,0,0,0,0,0,...,105277,105277,105277,105277,105277,105277,105277,105288,105288,https://public.flourish.studio/country-flags/s...

#### 1. 데이터프레임에서 필요한 컬럼만 선택하기
- 데이터프레임.columns.tolist() : 컬럼명을 리스트로 변환

<img src="https://davelee-fun.github.io/fixeddata/covid_data_format.png">

In [29]:
cols = doc_final_country.columns.tolist()
cols.remove('iso2')
cols.insert(1, 'iso2')
cols

['Country_Region',
 'iso2',
 '1/22/2020',
 '1/23/2020',
 '1/24/2020',
 '1/25/2020',
 '1/26/2020',
 '1/27/2020',
 '1/28/2020',
 '1/29/2020',
 '1/30/2020',
 '1/31/2020',
 '2/01/2020',
 '2/02/2020',
 '2/03/2020',
 '2/04/2020',
 '2/05/2020',
 '2/06/2020',
 '2/07/2020',
 '2/08/2020',
 '2/09/2020',
 '2/10/2020',
 '2/11/2020',
 '2/12/2020',
 '2/13/2020',
 '2/14/2020',
 '2/15/2020',
 '2/16/2020',
 '2/17/2020',
 '2/18/2020',
 '2/19/2020',
 '2/20/2020',
 '2/21/2020',
 '2/22/2020',
 '2/23/2020',
 '2/24/2020',
 '2/25/2020',
 '2/26/2020',
 '2/27/2020',
 '2/28/2020',
 '2/29/2020',
 '3/01/2020',
 '3/02/2020',
 '3/03/2020',
 '3/04/2020',
 '3/05/2020',
 '3/06/2020',
 '3/07/2020',
 '3/08/2020',
 '3/09/2020',
 '3/10/2020',
 '3/11/2020',
 '3/12/2020',
 '3/13/2020',
 '3/14/2020',
 '3/15/2020',
 '3/16/2020',
 '3/17/2020',
 '3/18/2020',
 '3/19/2020',
 '3/20/2020',
 '3/21/2020',
 '3/22/2020',
 '3/23/2020',
 '3/24/2020',
 '3/25/2020',
 '3/26/2020',
 '3/27/2020',
 '3/28/2020',
 '3/29/2020',
 '3/30/2020',
 '3/31/2020',
 '4/01/2020',
 '4/02/2020',
 '4/03/2020',
 '4/04/2020',
 '4/05/2020',
 '4/06/2020',
 '4/07/2020',
 '4/08/2020',
 '4/09/2020',
 '4/10/2020',
 '4/11/2020',
 '4/12/2020',
 '4/13/2020',
 '4/14/2020',
 '4/15/2020',
 '4/16/2020',
 '4/17/2020',
 '4/18/2020',
 '4/19/2020',
 '4/20/2020',
 '4/21/2020',
 '4/22/2020',
 '4/23/2020',
 '4/24/2020',
 '4/25/2020',
 '4/26/2020',
 '4/27/2020',
 '4/28/2020',
 '4/29/2020',
 '4/30/2020',
 '5/01/2020',
 '5/02/2020',
 '5/03/2020',
 '5/04/2020',
 '5/05/2020',
 '5/06/2020',
 '5/07/2020',
 '5/08/2020',
 '5/09/2020',
 '5/10/2020',
 '5/11/2020',
 '5/12/2020',
 '5/13/2020',
 '5/14/2020',
 '5/15/2020',
 '5/16/2020',
 '5/17/2020',
 '5/18/2020',
 '5/19/2020',
 '5/20/2020',
 '5/21/2020',
 '5/22/2020',
 '5/23/2020',
 '5/24/2020',
 '5/25/2020',
 '5/26/2020',
 '5/27/2020',
 '5/28/2020',
 '5/29/2020',
 '5/30/2020',
 '5/31/2020',
 '6/01/2020',
 '6/02/2020',
 '6/03/2020',
 '6/04/2020',
 '6/05/2020',
 '6/06/2020',
 '6/07/2020',
 '6/08/2020',
 '6/09/2020',
 '6/10/2020',
 '6/11/2020',
 '6/12/2020',
 '6/13/2020',
 '6/14/2020',
 '6/15/2020',
 '6/16/2020',
 '6/17/2020',
 '6/18/2020',
 '6/19/2020',
 '6/20/2020',
 '6/21/2020',
 '6/22/2020',
 '6/23/2020',
 '6/24/2020',
 '6/25/2020',
 '6/26/2020',
 '6/27/2020',
 '6/28/2020',
 '6/29/2020',
 '6/30/2020',
 '7/01/2020',
 '7/02/2020',
 '7/03/2020',
 '7/04/2020',
 '7/05/2020',
 '7/06/2020',
 '7/07/2020',
 '7/08/2020',
 '7/09/2020',
 '7/10/2020',
 '7/11/2020',
 '7/12/2020',
 '7/13/2020',
 '7/14/2020',
 '7/15/2020',
 '7/16/2020',
 '7/17/2020',
 '7/18/2020',
 '7/19/2020',
 '7/20/2020',
 '7/21/2020',
 '7/22/2020',
 '7/23/2020',
 '7/24/2020',
 '7/25/2020',
 '7/26/2020',
 '7/27/2020',
 '7/28/2020',
 '7/29/2020',
 '7/30/2020',
 '7/31/2020',
 '8/01/2020',
 '8/02/2020',
 '8/03/2020',
 '8/04/2020',
 '8/05/2020',
 '8/06/2020',
 '8/07/2020',
 '8/08/2020',
 '8/09/2020',
 '8/10/2020',
 '8/11/2020',
 '8/12/2020',
 '8/13/2020',
 '8/14/2020',
 '8/15/2020',
 '8/16/2020',
 '8/17/2020',
 '8/18/2020',
 '8/19/2020',
 '8/20/2020',
 '8/21/2020',
 '8/22/2020',
 '8/23/2020',
 '8/24/2020',
 '8/25/2020',
 '8/26/2020',
 '8/27/2020',
 '8/28/2020',
 '8/29/2020',
 '8/30/2020',
 '8/31/2020',
 '9/01/2020',
 '9/02/2020',
 '9/03/2020',
 '9/04/2020',
 '9/05/2020',
 '9/06/2020',
 '9/07/2020',
 '9/08/2020',
 '9/09/2020',
 '9/10/2020',
 '9/11/2020',
 '9/12/2020',
 '9/13/2020',
 '9/14/2020',
 '9/15/2020',
 '9/16/2020',
 '9/17/2020',
 '9/18/2020',
 '9/19/2020',
 '9/20/2020',
 '9/21/2020',
 '9/22/2020',
 '9/23/2020',
 '9/24/2020',
 '9/25/2020',
 '9/26/2020',
 '9/27/2020',
 '9/28/2020',
 '9/29/2020',
 '9/30/2020',
 '10/01/2020',
 '10/02/2020',
 '10/03/2020',
 '10/04/2020',
 '10/05/2020',
 '10/06/2020',
 '10/07/2020',
 '10/08/2020',
 '10/09/2020',
 '10/10/2020',
 '10/11/2020',
 '10/12/2020',
 '10/13/2020',
 '10/14/2020',
 '10/15/2020',
 '10/16/2020',
 '10/17/2020',
 '10/18/2020',
 '10/19/2020',
 '10/20/2020',
 '10/21/2020',
 '10/22/2020',
 '10/23/2020',
 '10/24/2020',
 '10/25/2020',
 '10/26/2020',
 '10/27/2020',
 '10/28/2020',
 '10/29/2020',
 '10/30/2020',
 '10/31/2020',
 '11/01/2020',
 '11/02/2020',
 '11/03/2020',
 '11/04/2020',
 '11/05/2020',
 '11/06/2020',
 '11/07/2020',
 '11/08/2020',
 '11/09/2020',
 '11/10/2020',
 '11/11/2020',
 '11/12/2020',
 '11/13/2020',
 '11/14/2020',
 '11/15/2020',
 '11/16/2020',
 '11/17/2020',
 '11/18/2020',
 '11/19/2020',
 '11/20/2020',
 '11/21/2020',
 '11/22/2020',
 '11/23/2020',
 '11/24/2020',
 '11/25/2020',
 '11/26/2020',
 '11/27/2020',
 '11/28/2020',
 '11/29/2020',
 '11/30/2020',
 '12/01/2020',
 '12/02/2020',
 '12/03/2020',
 '12/04/2020',
 '12/05/2020',
 '12/06/2020',
 '12/07/2020',
 '12/08/2020',
 '12/09/2020',
 '12/10/2020',
 '12/11/2020',
 '12/12/2020',
 '12/13/2020',
 '12/14/2020',
 '12/15/2020',
 '12/16/2020',
 '12/17/2020',
 '12/18/2020',
 '12/19/2020',
 '12/20/2020',
 '12/21/2020',
 '12/22/2020',
 '12/23/2020',
 '12/24/2020',
 '12/25/2020',
 '12/26/2020',
 '12/27/2020',
 '12/28/2020',
 '12/29/2020',
 '12/30/2020',
 '12/31/2020',
 '1/01/2021',
 '1/02/2021',
 '1/03/2021',
 '1/04/2021',
 '1/05/2021',
 '1/06/2021',
 '1/07/2021',
 '1/08/2021',
 '1/09/2021',
 '1/10/2021',
 '1/11/2021',
 '1/12/2021',
 '1/13/2021',
 '1/14/2021',
 '1/15/2021',
 '1/16/2021',
 '1/17/2021',
 '1/18/2021',
 '1/19/2021',
 '1/20/2021',
 '1/21/2021',
 '1/22/2021',
 '1/23/2021',
 '1/24/2021',
 '1/25/2021',
 '1/26/2021',
 '1/27/2021',
 '1/28/2021',
 '1/29/2021',
 '1/30/2021',
 '1/31/2021',
 '2/01/2021',
 '2/02/2021',
 '2/03/2021',
 '2/04/2021',
 '2/05/2021',
 '2/06/2021',
 '2/07/2021',
 '2/08/2021',
 '2/09/2021',
 '2/10/2021',
 '2/11/2021',
 '2/12/2021',
 '2/13/2021',
 '2/14/2021',
 '2/15/2021',
 '2/16/2021',
 '2/17/2021',
 '2/18/2021',
 '2/19/2021',
 '2/20/2021',
 '2/21/2021',
 '2/22/2021',
 '2/23/2021',
 '2/24/2021',
 '2/25/2021',
 '2/26/2021',
 '2/27/2021',
 '2/28/2021',
 '3/01/2021',
 '3/02/2021',
 '3/03/2021',
 '3/04/2021',
 '3/05/2021',
 '3/06/2021',
 '3/07/2021',
 '3/08/2021',
 '3/09/2021',
 '3/10/2021',
 '3/11/2021',
 '3/12/2021',
 '3/13/2021',
 '3/14/2021',
 '3/15/2021',
 '3/16/2021',
 '3/17/2021',
 '3/18/2021',
 '3/19/2021',
 '3/20/2021',
 '3/21/2021',
 '3/22/2021',
 '3/23/2021',
 '3/24/2021',
 '3/25/2021',
 '3/26/2021',
 '3/27/2021',
 '3/28/2021',
 '3/29/2021',
 '3/30/2021',
 '3/31/2021',
 '4/01/2021',
 '4/02/2021',
 '4/03/2021',
 '4/04/2021',
 '4/05/2021',
 '4/06/2021',
 '4/07/2021',
 '4/08/2021',
 '4/09/2021',
 '4/10/2021',
 '4/11/2021',
 '4/12/2021',
 '4/13/2021',
 '4/14/2021',
 '4/15/2021',
 '4/16/2021',
 '4/17/2021',
 '4/18/2021',
 '4/19/2021',
 '4/20/2021',
 '4/21/2021',
 '4/22/2021',
 '4/23/2021',
 '4/24/2021',
 '4/25/2021',
 '4/26/2021',
 '4/27/2021',
 '4/28/2021',
 '4/29/2021',
 '4/30/2021',
 '5/01/2021',
 '5/02/2021',
 '5/03/2021',
 '5/04/2021',
 '5/05/2021',
 '5/06/2021',
 '5/07/2021',
 '5/08/2021',
 '5/09/2021',
 '5/10/2021',
 '5/11/2021',
 '5/12/2021',
 '5/13/2021',
 '5/14/2021',
 '5/15/2021',
 '5/16/2021',
 '5/17/2021',
 '5/18/2021',
 '5/19/2021',
 '5/20/2021',
 '5/21/2021',
 '5/22/2021',
 '5/23/2021',
 '5/24/2021',
 '5/25/2021',
 '5/26/2021',
 '5/27/2021',
 '5/28/2021',
 '5/29/2021',
 '5/30/2021',
 '5/31/2021',
 '6/01/2021',
 '6/02/2021',
 '6/03/2021',
 '6/04/2021',
 '6/05/2021',
 '6/06/2021',
 '6/07/2021',
 '6/08/2021',
 '6/09/2021',
 '6/10/2021',
 '6/11/2021',
 '6/12/2021',
 '6/13/2021',
 '6/14/2021',
 '6/15/2021',
 '6/16/2021',
 '6/17/2021',
 '6/18/2021',
 '6/19/2021',
 '6/20/2021',
 '6/21/2021',
 '6/22/2021',
 '6/23/2021',
 '6/24/2021',
 '6/25/2021',
 '6/26/2021',
 '6/27/2021',
 '6/28/2021',
 '6/29/2021',
 '6/30/2021',
 '7/01/2021',
 '7/02/2021',
 '7/03/2021',
 '7/04/2021',
 '7/05/2021',
 '7/06/2021',
 '7/07/2021',
 '7/08/2021',
 '7/09/2021',
 '7/10/2021',
 '7/11/2021',
 '7/12/2021',
 '7/13/2021',
 '7/14/2021',
 '7/15/2021',
 '7/16/2021',
 '7/17/2021',
 '7/18/2021',
 '7/19/2021',
 '7/20/2021',
 '7/21/2021',
 '7/22/2021',
 '7/23/2021',
 '7/24/2021',
 '7/25/2021',
 '7/26/2021',
 '7/27/2021',
 '7/28/2021',
 '7/29/2021',
 '7/30/2021',
 '7/31/2021',
 '8/01/2021',
 '8/02/2021',
 '8/03/2021',
 '8/04/2021',
 '8/05/2021',
 '8/06/2021',
 '8/07/2021',
 '8/08/2021',
 '8/09/2021',
 '8/10/2021',
 '8/11/2021',
 '8/12/2021',
 '8/13/2021',
 '8/14/2021',
 '8/15/2021',
 '8/16/2021',
 '8/17/2021',
 '8/18/2021',
 '8/19/2021',
 '8/20/2021',
 '8/21/2021',
 '8/22/2021',
 '8/23/2021',
 '8/24/2021',
 '8/25/2021',
 '8/26/2021',
 '8/27/2021',
 '8/28/2021',
 '8/29/2021',
 '8/30/2021',
 '8/31/2021',
 '9/01/2021',
 '9/02/2021',
 '9/03/2021',
 '9/04/2021',
 '9/05/2021',
 '9/06/2021',
 '9/07/2021',
 '9/08/2021',
 '9/09/2021',
 '9/10/2021',
 '9/11/2021',
 '9/12/2021',
 '9/13/2021',
 '9/14/2021',
 '9/15/2021',
 '9/16/2021',
 '9/17/2021',
 '9/18/2021',
 '9/19/2021',
 '9/20/2021',
 '9/21/2021',
 '9/22/2021',
 '9/23/2021',
 '9/24/2021',
 '9/25/2021',
 '9/26/2021',
 '9/27/2021',
 '9/28/2021',
 '9/29/2021',
 '9/30/2021',
 '10/01/2021',
 '10/02/2021',
 '10/03/2021',
 '10/04/2021',
 '10/05/2021',
 '10/06/2021',
 '10/07/2021',
 '10/08/2021',
 '10/09/2021',
 '10/10/2021',
 '10/11/2021',
 '10/12/2021',
 '10/13/2021',
 '10/14/2021',
 '10/15/2021',
 '10/16/2021',
 '10/17/2021',
 '10/18/2021',
 '10/19/2021',
 '10/20/2021',
 '10/21/2021',
 '10/22/2021',
 '10/23/2021',
 '10/24/2021',
 '10/25/2021',
 '10/26/2021',
 '10/27/2021',
 '10/28/2021',
 '10/29/2021',
 '10/30/2021',
 '10/31/2021',
 '11/01/2021',
 '11/02/2021',
 '11/03/2021',
 '11/04/2021',
 '11/05/2021',
 '11/06/2021',
 '11/07/2021',
 '11/08/2021',
 '11/09/2021',
 '11/10/2021',
 '11/11/2021',
 '11/12/2021',
 '11/13/2021',
 '11/14/2021',
 '11/15/2021',
 '11/16/2021',
 '11/17/2021',
 '11/18/2021',
 '11/19/2021',
 '11/20/2021',
 '11/21/2021',
 '11/22/2021',
 '11/23/2021',
 '11/24/2021',
 '11/25/2021',
 '11/26/2021',
 '11/27/2021',
 '11/28/2021',
 '11/29/2021',
 '11/30/2021',
 '12/01/2021',
 '12/02/2021',
 '12/03/2021',
 '12/04/2021',
 '12/05/2021',
 '12/06/2021',
 '12/07/2021',
 '12/08/2021',
 '12/09/2021',
 '12/10/2021',
 '12/11/2021',
 '12/12/2021',
 '12/13/2021',
 '12/14/2021',
 '12/15/2021',
 '12/16/2021',
 '12/17/2021',
 '12/18/2021',
 '12/19/2021',
 '12/20/2021',
 '12/21/2021',
 '12/22/2021',
 '12/23/2021',
 '12/24/2021',
 '12/25/2021',
 '12/26/2021',
 '12/27/2021',
 '12/28/2021',
 '12/29/2021',
 '12/30/2021',
 '12/31/2021',
 '1/01/2022',
 '1/02/2022',
 '1/03/2022',
 '1/04/2022',
 '1/05/2022',
 '1/06/2022',
 '1/07/2022',
 '1/08/2022',
 '1/09/2022',
 '1/10/2022',
 '1/11/2022',
 '1/12/2022',
 '1/13/2022',
 '1/14/2022',
 '1/15/2022',
 '1/16/2022',
 '1/17/2022',
 '1/18/2022',
 '1/19/2022',
 '1/20/2022',
 '1/21/2022',
 '1/22/2022',
 '1/23/2022',
 '1/24/2022',
 '1/25/2022',
 '1/26/2022',
 '1/27/2022',
 '1/28/2022',
 '1/29/2022',
 '1/30/2022',
 '1/31/2022',
 '2/01/2022',
 '2/02/2022',
 '2/03/2022',
 '2/04/2022',
 '2/05/2022',
 '2/06/2022',
 '2/07/2022',
 '2/08/2022',
 '2/09/2022',
 '2/10/2022',
 '2/11/2022',
 '2/12/2022',
 '2/13/2022',
 '2/14/2022',
 '2/15/2022',
 '2/16/2022',
 '2/17/2022',
 '2/18/2022',
 '2/19/2022',
 '2/20/2022',
 '2/21/2022',
 '2/22/2022',
 '2/23/2022',
 '2/24/2022',
 '2/25/2022',
 '2/26/2022',
 '2/27/2022',
 '2/28/2022',
 '3/01/2022',
 '3/02/2022',
 '3/03/2022',
 '3/04/2022',
 '3/05/2022',
 '3/06/2022',
 '3/07/2022',
 '3/08/2022',
 '3/09/2022',
 '3/10/2022',
 '3/11/2022',
 '3/12/2022',
 '3/13/2022',
 '3/14/2022',
 '3/15/2022',
 '3/16/2022',
 '3/17/2022',
 '3/18/2022',
 '3/19/2022',
 '3/20/2022',
 '3/21/2022',
 '3/22/2022',
 '3/23/2022',
 '3/24/2022',
 '3/25/2022',
 '3/26/2022',
 '3/27/2022',
 '3/28/2022',
 '3/29/2022',
 '3/30/2022',
 '3/31/2022',
 '4/01/2022',
 '4/02/2022',
 '4/03/2022',
 '4/04/2022',
 '4/05/2022',
 '4/06/2022',
 '4/07/2022',
 '4/08/2022',
 '4/09/2022',
 '4/10/2022',
 '4/11/2022',
 '4/12/2022',
 '4/13/2022',
 '4/14/2022',
 '4/15/2022',
 '4/16/2022',
 '4/17/2022',
 '4/18/2022',
 '4/19/2022',
 '4/20/2022',
 '4/21/2022',
 '4/22/2022',
 '4/23/2022',
 '4/24/2022',
 '4/25/2022',
 '4/26/2022',
 '4/27/2022',
 '4/28/2022',
 '4/29/2022',
 '4/30/2022',
 '5/01/2022',
 '5/02/2022',
 '5/03/2022',
 '5/04/2022',
 '5/05/2022',
 '5/06/2022',
 '5/07/2022',
 '5/08/2022',
 '5/09/2022',
 '5/10/2022',
 '5/11/2022',
 '5/12/2022',
 '5/13/2022',
 '5/14/2022',
 '5/15/2022',
 '5/16/2022',
 '5/17/2022',
 '5/18/2022',
 '5/19/2022',
 '5/20/2022',
 '5/21/2022',
 '5/22/2022',
 '5/23/2022',
 '5/24/2022',
 '5/25/2022',
 '5/26/2022',
 '5/27/2022',
 '5/28/2022',
 '5/29/2022',
 '5/30/2022',
 '5/31/2022',
 '6/01/2022',
 '6/02/2022',
 '6/03/2022',
 '6/04/2022',
 '6/05/2022',
 '6/06/2022',
 '6/07/2022',
 '6/08/2022',
 '6/09/2022',
 '6/10/2022',
 '6/11/2022',
 '6/12/2022',
 '6/13/2022',
 '6/14/2022',
 '6/15/2022',
 '6/16/2022',
 '6/17/2022',
 '6/18/2022',
 '6/19/2022',
 '6/20/2022',
 '6/21/2022',
 '6/22/2022',
 '6/23/2022',
 '6/24/2022',
 '6/25/2022',
 '6/26/2022',
 '6/27/2022',
 '6/28/2022',
 '6/29/2022',
 '6/30/2022',
 '7/01/2022',
 '7/02/2022',
 '7/03/2022',
 '7/04/2022',
 '7/05/2022',
 '7/06/2022',
 '7/07/2022',
 '7/08/2022',
 '7/09/2022',
 '7/10/2022',
 '7/11/2022',
 '7/12/2022',
 '7/13/2022',
 '7/14/2022',
 '7/15/2022',
 '7/16/2022',
 '7/17/2022',
 '7/18/2022',
 '7/19/2022',
 '7/20/2022',
 '7/21/2022',
 '7/22/2022',
 '7/23/2022',
 '7/24/2022',
 '7/25/2022',
 '7/26/2022',
 '7/27/2022',
 '7/28/2022',
 '7/29/2022',
 '7/30/2022',
 '7/31/2022',
 '8/01/2022',
 '8/02/2022',
 '8/03/2022',
 '8/04/2022',
 '8/05/2022',
 '8/06/2022',
 '8/07/2022',
 '8/08/2022',
 '8/09/2022',
 '8/10/2022',
 '8/11/2022',
 '8/12/2022',
 '8/13/2022',
 '8/14/2022',
 '8/15/2022',
 '8/16/2022',
 '8/17/2022',
 '8/18/2022',
 '8/19/2022',
 '8/20/2022',
 '8/21/2022',
 '8/22/2022',
 '8/23/2022',
 '8/24/2022',
 '8/25/2022',
 '8/26/2022',
 '8/27/2022',
 '8/28/2022',
 '8/29/2022',
 '8/30/2022',
 '8/31/2022',
 '9/01/2022',
 '9/02/2022',
 '9/03/2022',
 '9/04/2022',
 '9/05/2022',
 '9/06/2022',
 '9/07/2022',
 '9/08/2022',
 '9/09/2022',
 '9/10/2022',
 '9/11/2022',
 '9/12/2022',
 '9/13/2022',
 '9/14/2022',
 '9/15/2022',
 '9/16/2022',
 '9/17/2022',
 '9/18/2022',
 '9/19/2022',
 '9/20/2022',
 '9/21/2022',
 '9/22/2022',
 '9/23/2022',
 '9/24/2022',
 '9/25/2022',
 '9/26/2022',
 '9/27/2022',
 '9/28/2022',
 '9/29/2022',
 '9/30/2022',
 '10/01/2022',
 '10/02/2022',
 '10/03/2022',
 '10/04/2022',
 '10/05/2022',
 '10/06/2022',
 '10/07/2022',
 '10/08/2022',
 '10/09/2022',
 '10/10/2022',
 '10/11/2022',
 '10/12/2022',
 '10/13/2022',
 '10/14/2022',
 '10/15/2022',
 ...]

#### 내가 정한 조건대로 정렬하기
- **`sorted(..., key=lambda x: pd.to_datetime(x, format='%m/%d/%Y'))`**:  
  - `sorted` 함수는 리스트를 정렬하여 새 리스트를 반환합니다.
  - **`key=lambda x: ...`**:  
    - 각 요소 `x`에 대해 정렬 기준을 지정합니다.
    - `x`는 날짜 형식의 문자열일 것으로 가정됩니다.
  - **`pd.to_datetime(x, format='%m/%d/%Y')`**:  
    - `x`를 지정된 날짜 포맷(`월/일/연도`)에 따라 datetime 객체로 변환합니다.
    - 변환된 datetime 객체를 기준으로 정렬되므로, 날짜 순서대로 정렬됩니다.

In [30]:
sorted(cols[2:], key=lambda x: pd.to_datetime(x, format='%m/%d/%Y'))

['1/22/2020',
 '1/23/2020',
 '1/24/2020',
 '1/25/2020',
 '1/26/2020',
 '1/27/2020',
 '1/28/2020',
 '1/29/2020',
 '1/30/2020',
 '1/31/2020',
 '2/01/2020',
 '2/02/2020',
 '2/03/2020',
 '2/04/2020',
 '2/05/2020',
 '2/06/2020',
 '2/07/2020',
 '2/08/2020',
 '2/09/2020',
 '2/10/2020',
 '2/11/2020',
 '2/12/2020',
 '2/13/2020',
 '2/14/2020',
 '2/15/2020',
 '2/16/2020',
 '2/17/2020',
 '2/18/2020',
 '2/19/2020',
 '2/20/2020',
 '2/21/2020',
 '2/22/2020',
 '2/23/2020',
 '2/24/2020',
 '2/25/2020',
 '2/26/2020',
 '2/27/2020',
 '2/28/2020',
 '2/29/2020',
 '3/01/2020',
 '3/02/2020',
 '3/03/2020',
 '3/04/2020',
 '3/05/2020',
 '3/06/2020',
 '3/07/2020',
 '3/08/2020',
 '3/09/2020',
 '3/10/2020',
 '3/11/2020',
 '3/12/2020',
 '3/13/2020',
 '3/14/2020',
 '3/15/2020',
 '3/16/2020',
 '3/17/2020',
 '3/18/2020',
 '3/19/2020',
 '3/20/2020',
 '3/21/2020',
 '3/22/2020',
 '3/23/2020',
 '3/24/2020',
 '3/25/2020',
 '3/26/2020',
 '3/27/2020',
 '3/28/2020',
 '3/29/2020',
 '3/30/2020',
 '3/31/2020',
 '4/01/2020',
 '4/02/2020',
 '4/03/2020',
 '4/04/2020',
 '4/05/2020',
 '4/06/2020',
 '4/07/2020',
 '4/08/2020',
 '4/09/2020',
 '4/10/2020',
 '4/11/2020',
 '4/12/2020',
 '4/13/2020',
 '4/14/2020',
 '4/15/2020',
 '4/16/2020',
 '4/17/2020',
 '4/18/2020',
 '4/19/2020',
 '4/20/2020',
 '4/21/2020',
 '4/22/2020',
 '4/23/2020',
 '4/24/2020',
 '4/25/2020',
 '4/26/2020',
 '4/27/2020',
 '4/28/2020',
 '4/29/2020',
 '4/30/2020',
 '5/01/2020',
 '5/02/2020',
 '5/03/2020',
 '5/04/2020',
 '5/05/2020',
 '5/06/2020',
 '5/07/2020',
 '5/08/2020',
 '5/09/2020',
 '5/10/2020',
 '5/11/2020',
 '5/12/2020',
 '5/13/2020',
 '5/14/2020',
 '5/15/2020',
 '5/16/2020',
 '5/17/2020',
 '5/18/2020',
 '5/19/2020',
 '5/20/2020',
 '5/21/2020',
 '5/22/2020',
 '5/23/2020',
 '5/24/2020',
 '5/25/2020',
 '5/26/2020',
 '5/27/2020',
 '5/28/2020',
 '5/29/2020',
 '5/30/2020',
 '5/31/2020',
 '6/01/2020',
 '6/02/2020',
 '6/03/2020',
 '6/04/2020',
 '6/05/2020',
 '6/06/2020',
 '6/07/2020',
 '6/08/2020',
 '6/09/2020',
 '6/10/2020',
 '6/11/2020',
 '6/12/2020',
 '6/13/2020',
 '6/14/2020',
 '6/15/2020',
 '6/16/2020',
 '6/17/2020',
 '6/18/2020',
 '6/19/2020',
 '6/20/2020',
 '6/21/2020',
 '6/22/2020',
 '6/23/2020',
 '6/24/2020',
 '6/25/2020',
 '6/26/2020',
 '6/27/2020',
 '6/28/2020',
 '6/29/2020',
 '6/30/2020',
 '7/01/2020',
 '7/02/2020',
 '7/03/2020',
 '7/04/2020',
 '7/05/2020',
 '7/06/2020',
 '7/07/2020',
 '7/08/2020',
 '7/09/2020',
 '7/10/2020',
 '7/11/2020',
 '7/12/2020',
 '7/13/2020',
 '7/14/2020',
 '7/15/2020',
 '7/16/2020',
 '7/17/2020',
 '7/18/2020',
 '7/19/2020',
 '7/20/2020',
 '7/21/2020',
 '7/22/2020',
 '7/23/2020',
 '7/24/2020',
 '7/25/2020',
 '7/26/2020',
 '7/27/2020',
 '7/28/2020',
 '7/29/2020',
 '7/30/2020',
 '7/31/2020',
 '8/01/2020',
 '8/02/2020',
 '8/03/2020',
 '8/04/2020',
 '8/05/2020',
 '8/06/2020',
 '8/07/2020',
 '8/08/2020',
 '8/09/2020',
 '8/10/2020',
 '8/11/2020',
 '8/12/2020',
 '8/13/2020',
 '8/14/2020',
 '8/15/2020',
 '8/16/2020',
 '8/17/2020',
 '8/18/2020',
 '8/19/2020',
 '8/20/2020',
 '8/21/2020',
 '8/22/2020',
 '8/23/2020',
 '8/24/2020',
 '8/25/2020',
 '8/26/2020',
 '8/27/2020',
 '8/28/2020',
 '8/29/2020',
 '8/30/2020',
 '8/31/2020',
 '9/01/2020',
 '9/02/2020',
 '9/03/2020',
 '9/04/2020',
 '9/05/2020',
 '9/06/2020',
 '9/07/2020',
 '9/08/2020',
 '9/09/2020',
 '9/10/2020',
 '9/11/2020',
 '9/12/2020',
 '9/13/2020',
 '9/14/2020',
 '9/15/2020',
 '9/16/2020',
 '9/17/2020',
 '9/18/2020',
 '9/19/2020',
 '9/20/2020',
 '9/21/2020',
 '9/22/2020',
 '9/23/2020',
 '9/24/2020',
 '9/25/2020',
 '9/26/2020',
 '9/27/2020',
 '9/28/2020',
 '9/29/2020',
 '9/30/2020',
 '10/01/2020',
 '10/02/2020',
 '10/03/2020',
 '10/04/2020',
 '10/05/2020',
 '10/06/2020',
 '10/07/2020',
 '10/08/2020',
 '10/09/2020',
 '10/10/2020',
 '10/11/2020',
 '10/12/2020',
 '10/13/2020',
 '10/14/2020',
 '10/15/2020',
 '10/16/2020',
 '10/17/2020',
 '10/18/2020',
 '10/19/2020',
 '10/20/2020',
 '10/21/2020',
 '10/22/2020',
 '10/23/2020',
 '10/24/2020',
 '10/25/2020',
 '10/26/2020',
 '10/27/2020',
 '10/28/2020',
 '10/29/2020',
 '10/30/2020',
 '10/31/2020',
 '11/01/2020',
 '11/02/2020',
 '11/03/2020',
 '11/04/2020',
 '11/05/2020',
 '11/06/2020',
 '11/07/2020',
 '11/08/2020',
 '11/09/2020',
 '11/10/2020',
 '11/11/2020',
 '11/12/2020',
 '11/13/2020',
 '11/14/2020',
 '11/15/2020',
 '11/16/2020',
 '11/17/2020',
 '11/18/2020',
 '11/19/2020',
 '11/20/2020',
 '11/21/2020',
 '11/22/2020',
 '11/23/2020',
 '11/24/2020',
 '11/25/2020',
 '11/26/2020',
 '11/27/2020',
 '11/28/2020',
 '11/29/2020',
 '11/30/2020',
 '12/01/2020',
 '12/02/2020',
 '12/03/2020',
 '12/04/2020',
 '12/05/2020',
 '12/06/2020',
 '12/07/2020',
 '12/08/2020',
 '12/09/2020',
 '12/10/2020',
 '12/11/2020',
 '12/12/2020',
 '12/13/2020',
 '12/14/2020',
 '12/15/2020',
 '12/16/2020',
 '12/17/2020',
 '12/18/2020',
 '12/19/2020',
 '12/20/2020',
 '12/21/2020',
 '12/22/2020',
 '12/23/2020',
 '12/24/2020',
 '12/25/2020',
 '12/26/2020',
 '12/27/2020',
 '12/28/2020',
 '12/29/2020',
 '12/30/2020',
 '12/31/2020',
 '1/01/2021',
 '1/02/2021',
 '1/03/2021',
 '1/04/2021',
 '1/05/2021',
 '1/06/2021',
 '1/07/2021',
 '1/08/2021',
 '1/09/2021',
 '1/10/2021',
 '1/11/2021',
 '1/12/2021',
 '1/13/2021',
 '1/14/2021',
 '1/15/2021',
 '1/16/2021',
 '1/17/2021',
 '1/18/2021',
 '1/19/2021',
 '1/20/2021',
 '1/21/2021',
 '1/22/2021',
 '1/23/2021',
 '1/24/2021',
 '1/25/2021',
 '1/26/2021',
 '1/27/2021',
 '1/28/2021',
 '1/29/2021',
 '1/30/2021',
 '1/31/2021',
 '2/01/2021',
 '2/02/2021',
 '2/03/2021',
 '2/04/2021',
 '2/05/2021',
 '2/06/2021',
 '2/07/2021',
 '2/08/2021',
 '2/09/2021',
 '2/10/2021',
 '2/11/2021',
 '2/12/2021',
 '2/13/2021',
 '2/14/2021',
 '2/15/2021',
 '2/16/2021',
 '2/17/2021',
 '2/18/2021',
 '2/19/2021',
 '2/20/2021',
 '2/21/2021',
 '2/22/2021',
 '2/23/2021',
 '2/24/2021',
 '2/25/2021',
 '2/26/2021',
 '2/27/2021',
 '2/28/2021',
 '3/01/2021',
 '3/02/2021',
 '3/03/2021',
 '3/04/2021',
 '3/05/2021',
 '3/06/2021',
 '3/07/2021',
 '3/08/2021',
 '3/09/2021',
 '3/10/2021',
 '3/11/2021',
 '3/12/2021',
 '3/13/2021',
 '3/14/2021',
 '3/15/2021',
 '3/16/2021',
 '3/17/2021',
 '3/18/2021',
 '3/19/2021',
 '3/20/2021',
 '3/21/2021',
 '3/22/2021',
 '3/23/2021',
 '3/24/2021',
 '3/25/2021',
 '3/26/2021',
 '3/27/2021',
 '3/28/2021',
 '3/29/2021',
 '3/30/2021',
 '3/31/2021',
 '4/01/2021',
 '4/02/2021',
 '4/03/2021',
 '4/04/2021',
 '4/05/2021',
 '4/06/2021',
 '4/07/2021',
 '4/08/2021',
 '4/09/2021',
 '4/10/2021',
 '4/11/2021',
 '4/12/2021',
 '4/13/2021',
 '4/14/2021',
 '4/15/2021',
 '4/16/2021',
 '4/17/2021',
 '4/18/2021',
 '4/19/2021',
 '4/20/2021',
 '4/21/2021',
 '4/22/2021',
 '4/23/2021',
 '4/24/2021',
 '4/25/2021',
 '4/26/2021',
 '4/27/2021',
 '4/28/2021',
 '4/29/2021',
 '4/30/2021',
 '5/01/2021',
 '5/02/2021',
 '5/03/2021',
 '5/04/2021',
 '5/05/2021',
 '5/06/2021',
 '5/07/2021',
 '5/08/2021',
 '5/09/2021',
 '5/10/2021',
 '5/11/2021',
 '5/12/2021',
 '5/13/2021',
 '5/14/2021',
 '5/15/2021',
 '5/16/2021',
 '5/17/2021',
 '5/18/2021',
 '5/19/2021',
 '5/20/2021',
 '5/21/2021',
 '5/22/2021',
 '5/23/2021',
 '5/24/2021',
 '5/25/2021',
 '5/26/2021',
 '5/27/2021',
 '5/28/2021',
 '5/29/2021',
 '5/30/2021',
 '5/31/2021',
 '6/01/2021',
 '6/02/2021',
 '6/03/2021',
 '6/04/2021',
 '6/05/2021',
 '6/06/2021',
 '6/07/2021',
 '6/08/2021',
 '6/09/2021',
 '6/10/2021',
 '6/11/2021',
 '6/12/2021',
 '6/13/2021',
 '6/14/2021',
 '6/15/2021',
 '6/16/2021',
 '6/17/2021',
 '6/18/2021',
 '6/19/2021',
 '6/20/2021',
 '6/21/2021',
 '6/22/2021',
 '6/23/2021',
 '6/24/2021',
 '6/25/2021',
 '6/26/2021',
 '6/27/2021',
 '6/28/2021',
 '6/29/2021',
 '6/30/2021',
 '7/01/2021',
 '7/02/2021',
 '7/03/2021',
 '7/04/2021',
 '7/05/2021',
 '7/06/2021',
 '7/07/2021',
 '7/08/2021',
 '7/09/2021',
 '7/10/2021',
 '7/11/2021',
 '7/12/2021',
 '7/13/2021',
 '7/14/2021',
 '7/15/2021',
 '7/16/2021',
 '7/17/2021',
 '7/18/2021',
 '7/19/2021',
 '7/20/2021',
 '7/21/2021',
 '7/22/2021',
 '7/23/2021',
 '7/24/2021',
 '7/25/2021',
 '7/26/2021',
 '7/27/2021',
 '7/28/2021',
 '7/29/2021',
 '7/30/2021',
 '7/31/2021',
 '8/01/2021',
 '8/02/2021',
 '8/03/2021',
 '8/04/2021',
 '8/05/2021',
 '8/06/2021',
 '8/07/2021',
 '8/08/2021',
 '8/09/2021',
 '8/10/2021',
 '8/11/2021',
 '8/12/2021',
 '8/13/2021',
 '8/14/2021',
 '8/15/2021',
 '8/16/2021',
 '8/17/2021',
 '8/18/2021',
 '8/19/2021',
 '8/20/2021',
 '8/21/2021',
 '8/22/2021',
 '8/23/2021',
 '8/24/2021',
 '8/25/2021',
 '8/26/2021',
 '8/27/2021',
 '8/28/2021',
 '8/29/2021',
 '8/30/2021',
 '8/31/2021',
 '9/01/2021',
 '9/02/2021',
 '9/03/2021',
 '9/04/2021',
 '9/05/2021',
 '9/06/2021',
 '9/07/2021',
 '9/08/2021',
 '9/09/2021',
 '9/10/2021',
 '9/11/2021',
 '9/12/2021',
 '9/13/2021',
 '9/14/2021',
 '9/15/2021',
 '9/16/2021',
 '9/17/2021',
 '9/18/2021',
 '9/19/2021',
 '9/20/2021',
 '9/21/2021',
 '9/22/2021',
 '9/23/2021',
 '9/24/2021',
 '9/25/2021',
 '9/26/2021',
 '9/27/2021',
 '9/28/2021',
 '9/29/2021',
 '9/30/2021',
 '10/01/2021',
 '10/02/2021',
 '10/03/2021',
 '10/04/2021',
 '10/05/2021',
 '10/06/2021',
 '10/07/2021',
 '10/08/2021',
 '10/09/2021',
 '10/10/2021',
 '10/11/2021',
 '10/12/2021',
 '10/13/2021',
 '10/14/2021',
 '10/15/2021',
 '10/16/2021',
 '10/17/2021',
 '10/18/2021',
 '10/19/2021',
 '10/20/2021',
 '10/21/2021',
 '10/22/2021',
 '10/23/2021',
 '10/24/2021',
 '10/25/2021',
 '10/26/2021',
 '10/27/2021',
 '10/28/2021',
 '10/29/2021',
 '10/30/2021',
 '10/31/2021',
 '11/01/2021',
 '11/02/2021',
 '11/03/2021',
 '11/04/2021',
 '11/05/2021',
 '11/06/2021',
 '11/07/2021',
 '11/08/2021',
 '11/09/2021',
 '11/10/2021',
 '11/11/2021',
 '11/12/2021',
 '11/13/2021',
 '11/14/2021',
 '11/15/2021',
 '11/16/2021',
 '11/17/2021',
 '11/18/2021',
 '11/19/2021',
 '11/20/2021',
 '11/21/2021',
 '11/22/2021',
 '11/23/2021',
 '11/24/2021',
 '11/25/2021',
 '11/26/2021',
 '11/27/2021',
 '11/28/2021',
 '11/29/2021',
 '11/30/2021',
 '12/01/2021',
 '12/02/2021',
 '12/03/2021',
 '12/04/2021',
 '12/05/2021',
 '12/06/2021',
 '12/07/2021',
 '12/08/2021',
 '12/09/2021',
 '12/10/2021',
 '12/11/2021',
 '12/12/2021',
 '12/13/2021',
 '12/14/2021',
 '12/15/2021',
 '12/16/2021',
 '12/17/2021',
 '12/18/2021',
 '12/19/2021',
 '12/20/2021',
 '12/21/2021',
 '12/22/2021',
 '12/23/2021',
 '12/24/2021',
 '12/25/2021',
 '12/26/2021',
 '12/27/2021',
 '12/28/2021',
 '12/29/2021',
 '12/30/2021',
 '12/31/2021',
 '1/01/2022',
 '1/02/2022',
 '1/03/2022',
 '1/04/2022',
 '1/05/2022',
 '1/06/2022',
 '1/07/2022',
 '1/08/2022',
 '1/09/2022',
 '1/10/2022',
 '1/11/2022',
 '1/12/2022',
 '1/13/2022',
 '1/14/2022',
 '1/15/2022',
 '1/16/2022',
 '1/17/2022',
 '1/18/2022',
 '1/19/2022',
 '1/20/2022',
 '1/21/2022',
 '1/22/2022',
 '1/23/2022',
 '1/24/2022',
 '1/25/2022',
 '1/26/2022',
 '1/27/2022',
 '1/28/2022',
 '1/29/2022',
 '1/30/2022',
 '1/31/2022',
 '2/01/2022',
 '2/02/2022',
 '2/03/2022',
 '2/04/2022',
 '2/05/2022',
 '2/06/2022',
 '2/07/2022',
 '2/08/2022',
 '2/09/2022',
 '2/10/2022',
 '2/11/2022',
 '2/12/2022',
 '2/13/2022',
 '2/14/2022',
 '2/15/2022',
 '2/16/2022',
 '2/17/2022',
 '2/18/2022',
 '2/19/2022',
 '2/20/2022',
 '2/21/2022',
 '2/22/2022',
 '2/23/2022',
 '2/24/2022',
 '2/25/2022',
 '2/26/2022',
 '2/27/2022',
 '2/28/2022',
 '3/01/2022',
 '3/02/2022',
 '3/03/2022',
 '3/04/2022',
 '3/05/2022',
 '3/06/2022',
 '3/07/2022',
 '3/08/2022',
 '3/09/2022',
 '3/10/2022',
 '3/11/2022',
 '3/12/2022',
 '3/13/2022',
 '3/14/2022',
 '3/15/2022',
 '3/16/2022',
 '3/17/2022',
 '3/18/2022',
 '3/19/2022',
 '3/20/2022',
 '3/21/2022',
 '3/22/2022',
 '3/23/2022',
 '3/24/2022',
 '3/25/2022',
 '3/26/2022',
 '3/27/2022',
 '3/28/2022',
 '3/29/2022',
 '3/30/2022',
 '3/31/2022',
 '4/01/2022',
 '4/02/2022',
 '4/03/2022',
 '4/04/2022',
 '4/05/2022',
 '4/06/2022',
 '4/07/2022',
 '4/08/2022',
 '4/09/2022',
 '4/10/2022',
 '4/11/2022',
 '4/12/2022',
 '4/13/2022',
 '4/14/2022',
 '4/15/2022',
 '4/16/2022',
 '4/17/2022',
 '4/18/2022',
 '4/19/2022',
 '4/20/2022',
 '4/21/2022',
 '4/22/2022',
 '4/23/2022',
 '4/24/2022',
 '4/25/2022',
 '4/26/2022',
 '4/27/2022',
 '4/28/2022',
 '4/29/2022',
 '4/30/2022',
 '5/01/2022',
 '5/02/2022',
 '5/03/2022',
 '5/04/2022',
 '5/05/2022',
 '5/06/2022',
 '5/07/2022',
 '5/08/2022',
 '5/09/2022',
 '5/10/2022',
 '5/11/2022',
 '5/12/2022',
 '5/13/2022',
 '5/14/2022',
 '5/15/2022',
 '5/16/2022',
 '5/17/2022',
 '5/18/2022',
 '5/19/2022',
 '5/20/2022',
 '5/21/2022',
 '5/22/2022',
 '5/23/2022',
 '5/24/2022',
 '5/25/2022',
 '5/26/2022',
 '5/27/2022',
 '5/28/2022',
 '5/29/2022',
 '5/30/2022',
 '5/31/2022',
 '6/01/2022',
 '6/02/2022',
 '6/03/2022',
 '6/04/2022',
 '6/05/2022',
 '6/06/2022',
 '6/07/2022',
 '6/08/2022',
 '6/09/2022',
 '6/10/2022',
 '6/11/2022',
 '6/12/2022',
 '6/13/2022',
 '6/14/2022',
 '6/15/2022',
 '6/16/2022',
 '6/17/2022',
 '6/18/2022',
 '6/19/2022',
 '6/20/2022',
 '6/21/2022',
 '6/22/2022',
 '6/23/2022',
 '6/24/2022',
 '6/25/2022',
 '6/26/2022',
 '6/27/2022',
 '6/28/2022',
 '6/29/2022',
 '6/30/2022',
 '7/01/2022',
 '7/02/2022',
 '7/03/2022',
 '7/04/2022',
 '7/05/2022',
 '7/06/2022',
 '7/07/2022',
 '7/08/2022',
 '7/09/2022',
 '7/10/2022',
 '7/11/2022',
 '7/12/2022',
 '7/13/2022',
 '7/14/2022',
 '7/15/2022',
 '7/16/2022',
 '7/17/2022',
 '7/18/2022',
 '7/19/2022',
 '7/20/2022',
 '7/21/2022',
 '7/22/2022',
 '7/23/2022',
 '7/24/2022',
 '7/25/2022',
 '7/26/2022',
 '7/27/2022',
 '7/28/2022',
 '7/29/2022',
 '7/30/2022',
 '7/31/2022',
 '8/01/2022',
 '8/02/2022',
 '8/03/2022',
 '8/04/2022',
 '8/05/2022',
 '8/06/2022',
 '8/07/2022',
 '8/08/2022',
 '8/09/2022',
 '8/10/2022',
 '8/11/2022',
 '8/12/2022',
 '8/13/2022',
 '8/14/2022',
 '8/15/2022',
 '8/16/2022',
 '8/17/2022',
 '8/18/2022',
 '8/19/2022',
 '8/20/2022',
 '8/21/2022',
 '8/22/2022',
 '8/23/2022',
 '8/24/2022',
 '8/25/2022',
 '8/26/2022',
 '8/27/2022',
 '8/28/2022',
 '8/29/2022',
 '8/30/2022',
 '8/31/2022',
 '9/01/2022',
 '9/02/2022',
 '9/03/2022',
 '9/04/2022',
 '9/05/2022',
 '9/06/2022',
 '9/07/2022',
 '9/08/2022',
 '9/09/2022',
 '9/10/2022',
 '9/11/2022',
 '9/12/2022',
 '9/13/2022',
 '9/14/2022',
 '9/15/2022',
 '9/16/2022',
 '9/17/2022',
 '9/18/2022',
 '9/19/2022',
 '9/20/2022',
 '9/21/2022',
 '9/22/2022',
 '9/23/2022',
 '9/24/2022',
 '9/25/2022',
 '9/26/2022',
 '9/27/2022',
 '9/28/2022',
 '9/29/2022',
 '9/30/2022',
 '10/01/2022',
 '10/02/2022',
 '10/03/2022',
 '10/04/2022',
 '10/05/2022',
 '10/06/2022',
 '10/07/2022',
 '10/08/2022',
 '10/09/2022',
 '10/10/2022',
 '10/11/2022',
 '10/12/2022',
 '10/13/2022',
 '10/14/2022',
 '10/15/2022',
 '10/16/2022',
 '10/17/2022',
 ...]

#### 참고: 오름차순 정렬과 내림차순 정렬
- **오름차순 정렬 (낮은 순)**  
  기본적으로 `sorted` 함수는 오름차순 정렬(가장 작은 값부터 큰 값 순)을 수행합니다. 날짜의 경우, 이는 **이른 날짜부터 늦은 날짜** 순으로 정렬됨을 의미합니다.
  
  예시:
  ```python
  # 이른 날짜(낮은 값) -> 늦은 날짜(높은 값) 순
  sorted_list = sorted(cols[2:], key=lambda x: pd.to_datetime(x, format='%m/%d/%Y'))
  ```

- **내림차순 정렬 (높은 순)**  
  내림차순 정렬(큰 값부터 작은 값 순)을 원한다면, `sorted` 함수의 `reverse` 매개변수를 `True`로 설정하면 됩니다. 날짜의 경우, 이는 **늦은 날짜부터 이른 날짜** 순으로 정렬됨을 의미합니다.
  
  예시:
  ```python
  # 늦은 날짜(높은 값) -> 이른 날짜(낮은 값) 순
  sorted_list_desc = sorted(cols[2:], key=lambda x: pd.to_datetime(x, format='%m/%d/%Y'), reverse=True)
  ```

이처럼 `reverse` 매개변수를 통해 날짜 정렬의 순서를 쉽게 조절할 수 있습니다.  
- `reverse=False` 또는 생략 시: 오름차순 (낮은 순)  
- `reverse=True` 시: 내림차순 (높은 순)

#### 리스트 합치기
- 리스트타입 + 리스트타입 으로 리스트를 합칠 수 있음

In [31]:
cols = cols[:2] + sorted(cols[2:], key=lambda x: pd.to_datetime(x, format='%m/%d/%Y'))
cols

['Country_Region',
 'iso2',
 '1/22/2020',
 '1/23/2020',
 '1/24/2020',
 '1/25/2020',
 '1/26/2020',
 '1/27/2020',
 '1/28/2020',
 '1/29/2020',
 '1/30/2020',
 '1/31/2020',
 '2/01/2020',
 '2/02/2020',
 '2/03/2020',
 '2/04/2020',
 '2/05/2020',
 '2/06/2020',
 '2/07/2020',
 '2/08/2020',
 '2/09/2020',
 '2/10/2020',
 '2/11/2020',
 '2/12/2020',
 '2/13/2020',
 '2/14/2020',
 '2/15/2020',
 '2/16/2020',
 '2/17/2020',
 '2/18/2020',
 '2/19/2020',
 '2/20/2020',
 '2/21/2020',
 '2/22/2020',
 '2/23/2020',
 '2/24/2020',
 '2/25/2020',
 '2/26/2020',
 '2/27/2020',
 '2/28/2020',
 '2/29/2020',
 '3/01/2020',
 '3/02/2020',
 '3/03/2020',
 '3/04/2020',
 '3/05/2020',
 '3/06/2020',
 '3/07/2020',
 '3/08/2020',
 '3/09/2020',
 '3/10/2020',
 '3/11/2020',
 '3/12/2020',
 '3/13/2020',
 '3/14/2020',
 '3/15/2020',
 '3/16/2020',
 '3/17/2020',
 '3/18/2020',
 '3/19/2020',
 '3/20/2020',
 '3/21/2020',
 '3/22/2020',
 '3/23/2020',
 '3/24/2020',
 '3/25/2020',
 '3/26/2020',
 '3/27/2020',
 '3/28/2020',
 '3/29/2020',
 '3/30/2020',
 '3/31/2020',
 '4/01/2020',
 '4/02/2020',
 '4/03/2020',
 '4/04/2020',
 '4/05/2020',
 '4/06/2020',
 '4/07/2020',
 '4/08/2020',
 '4/09/2020',
 '4/10/2020',
 '4/11/2020',
 '4/12/2020',
 '4/13/2020',
 '4/14/2020',
 '4/15/2020',
 '4/16/2020',
 '4/17/2020',
 '4/18/2020',
 '4/19/2020',
 '4/20/2020',
 '4/21/2020',
 '4/22/2020',
 '4/23/2020',
 '4/24/2020',
 '4/25/2020',
 '4/26/2020',
 '4/27/2020',
 '4/28/2020',
 '4/29/2020',
 '4/30/2020',
 '5/01/2020',
 '5/02/2020',
 '5/03/2020',
 '5/04/2020',
 '5/05/2020',
 '5/06/2020',
 '5/07/2020',
 '5/08/2020',
 '5/09/2020',
 '5/10/2020',
 '5/11/2020',
 '5/12/2020',
 '5/13/2020',
 '5/14/2020',
 '5/15/2020',
 '5/16/2020',
 '5/17/2020',
 '5/18/2020',
 '5/19/2020',
 '5/20/2020',
 '5/21/2020',
 '5/22/2020',
 '5/23/2020',
 '5/24/2020',
 '5/25/2020',
 '5/26/2020',
 '5/27/2020',
 '5/28/2020',
 '5/29/2020',
 '5/30/2020',
 '5/31/2020',
 '6/01/2020',
 '6/02/2020',
 '6/03/2020',
 '6/04/2020',
 '6/05/2020',
 '6/06/2020',
 '6/07/2020',
 '6/08/2020',
 '6/09/2020',
 '6/10/2020',
 '6/11/2020',
 '6/12/2020',
 '6/13/2020',
 '6/14/2020',
 '6/15/2020',
 '6/16/2020',
 '6/17/2020',
 '6/18/2020',
 '6/19/2020',
 '6/20/2020',
 '6/21/2020',
 '6/22/2020',
 '6/23/2020',
 '6/24/2020',
 '6/25/2020',
 '6/26/2020',
 '6/27/2020',
 '6/28/2020',
 '6/29/2020',
 '6/30/2020',
 '7/01/2020',
 '7/02/2020',
 '7/03/2020',
 '7/04/2020',
 '7/05/2020',
 '7/06/2020',
 '7/07/2020',
 '7/08/2020',
 '7/09/2020',
 '7/10/2020',
 '7/11/2020',
 '7/12/2020',
 '7/13/2020',
 '7/14/2020',
 '7/15/2020',
 '7/16/2020',
 '7/17/2020',
 '7/18/2020',
 '7/19/2020',
 '7/20/2020',
 '7/21/2020',
 '7/22/2020',
 '7/23/2020',
 '7/24/2020',
 '7/25/2020',
 '7/26/2020',
 '7/27/2020',
 '7/28/2020',
 '7/29/2020',
 '7/30/2020',
 '7/31/2020',
 '8/01/2020',
 '8/02/2020',
 '8/03/2020',
 '8/04/2020',
 '8/05/2020',
 '8/06/2020',
 '8/07/2020',
 '8/08/2020',
 '8/09/2020',
 '8/10/2020',
 '8/11/2020',
 '8/12/2020',
 '8/13/2020',
 '8/14/2020',
 '8/15/2020',
 '8/16/2020',
 '8/17/2020',
 '8/18/2020',
 '8/19/2020',
 '8/20/2020',
 '8/21/2020',
 '8/22/2020',
 '8/23/2020',
 '8/24/2020',
 '8/25/2020',
 '8/26/2020',
 '8/27/2020',
 '8/28/2020',
 '8/29/2020',
 '8/30/2020',
 '8/31/2020',
 '9/01/2020',
 '9/02/2020',
 '9/03/2020',
 '9/04/2020',
 '9/05/2020',
 '9/06/2020',
 '9/07/2020',
 '9/08/2020',
 '9/09/2020',
 '9/10/2020',
 '9/11/2020',
 '9/12/2020',
 '9/13/2020',
 '9/14/2020',
 '9/15/2020',
 '9/16/2020',
 '9/17/2020',
 '9/18/2020',
 '9/19/2020',
 '9/20/2020',
 '9/21/2020',
 '9/22/2020',
 '9/23/2020',
 '9/24/2020',
 '9/25/2020',
 '9/26/2020',
 '9/27/2020',
 '9/28/2020',
 '9/29/2020',
 '9/30/2020',
 '10/01/2020',
 '10/02/2020',
 '10/03/2020',
 '10/04/2020',
 '10/05/2020',
 '10/06/2020',
 '10/07/2020',
 '10/08/2020',
 '10/09/2020',
 '10/10/2020',
 '10/11/2020',
 '10/12/2020',
 '10/13/2020',
 '10/14/2020',
 '10/15/2020',
 '10/16/2020',
 '10/17/2020',
 '10/18/2020',
 '10/19/2020',
 '10/20/2020',
 '10/21/2020',
 '10/22/2020',
 '10/23/2020',
 '10/24/2020',
 '10/25/2020',
 '10/26/2020',
 '10/27/2020',
 '10/28/2020',
 '10/29/2020',
 '10/30/2020',
 '10/31/2020',
 '11/01/2020',
 '11/02/2020',
 '11/03/2020',
 '11/04/2020',
 '11/05/2020',
 '11/06/2020',
 '11/07/2020',
 '11/08/2020',
 '11/09/2020',
 '11/10/2020',
 '11/11/2020',
 '11/12/2020',
 '11/13/2020',
 '11/14/2020',
 '11/15/2020',
 '11/16/2020',
 '11/17/2020',
 '11/18/2020',
 '11/19/2020',
 '11/20/2020',
 '11/21/2020',
 '11/22/2020',
 '11/23/2020',
 '11/24/2020',
 '11/25/2020',
 '11/26/2020',
 '11/27/2020',
 '11/28/2020',
 '11/29/2020',
 '11/30/2020',
 '12/01/2020',
 '12/02/2020',
 '12/03/2020',
 '12/04/2020',
 '12/05/2020',
 '12/06/2020',
 '12/07/2020',
 '12/08/2020',
 '12/09/2020',
 '12/10/2020',
 '12/11/2020',
 '12/12/2020',
 '12/13/2020',
 '12/14/2020',
 '12/15/2020',
 '12/16/2020',
 '12/17/2020',
 '12/18/2020',
 '12/19/2020',
 '12/20/2020',
 '12/21/2020',
 '12/22/2020',
 '12/23/2020',
 '12/24/2020',
 '12/25/2020',
 '12/26/2020',
 '12/27/2020',
 '12/28/2020',
 '12/29/2020',
 '12/30/2020',
 '12/31/2020',
 '1/01/2021',
 '1/02/2021',
 '1/03/2021',
 '1/04/2021',
 '1/05/2021',
 '1/06/2021',
 '1/07/2021',
 '1/08/2021',
 '1/09/2021',
 '1/10/2021',
 '1/11/2021',
 '1/12/2021',
 '1/13/2021',
 '1/14/2021',
 '1/15/2021',
 '1/16/2021',
 '1/17/2021',
 '1/18/2021',
 '1/19/2021',
 '1/20/2021',
 '1/21/2021',
 '1/22/2021',
 '1/23/2021',
 '1/24/2021',
 '1/25/2021',
 '1/26/2021',
 '1/27/2021',
 '1/28/2021',
 '1/29/2021',
 '1/30/2021',
 '1/31/2021',
 '2/01/2021',
 '2/02/2021',
 '2/03/2021',
 '2/04/2021',
 '2/05/2021',
 '2/06/2021',
 '2/07/2021',
 '2/08/2021',
 '2/09/2021',
 '2/10/2021',
 '2/11/2021',
 '2/12/2021',
 '2/13/2021',
 '2/14/2021',
 '2/15/2021',
 '2/16/2021',
 '2/17/2021',
 '2/18/2021',
 '2/19/2021',
 '2/20/2021',
 '2/21/2021',
 '2/22/2021',
 '2/23/2021',
 '2/24/2021',
 '2/25/2021',
 '2/26/2021',
 '2/27/2021',
 '2/28/2021',
 '3/01/2021',
 '3/02/2021',
 '3/03/2021',
 '3/04/2021',
 '3/05/2021',
 '3/06/2021',
 '3/07/2021',
 '3/08/2021',
 '3/09/2021',
 '3/10/2021',
 '3/11/2021',
 '3/12/2021',
 '3/13/2021',
 '3/14/2021',
 '3/15/2021',
 '3/16/2021',
 '3/17/2021',
 '3/18/2021',
 '3/19/2021',
 '3/20/2021',
 '3/21/2021',
 '3/22/2021',
 '3/23/2021',
 '3/24/2021',
 '3/25/2021',
 '3/26/2021',
 '3/27/2021',
 '3/28/2021',
 '3/29/2021',
 '3/30/2021',
 '3/31/2021',
 '4/01/2021',
 '4/02/2021',
 '4/03/2021',
 '4/04/2021',
 '4/05/2021',
 '4/06/2021',
 '4/07/2021',
 '4/08/2021',
 '4/09/2021',
 '4/10/2021',
 '4/11/2021',
 '4/12/2021',
 '4/13/2021',
 '4/14/2021',
 '4/15/2021',
 '4/16/2021',
 '4/17/2021',
 '4/18/2021',
 '4/19/2021',
 '4/20/2021',
 '4/21/2021',
 '4/22/2021',
 '4/23/2021',
 '4/24/2021',
 '4/25/2021',
 '4/26/2021',
 '4/27/2021',
 '4/28/2021',
 '4/29/2021',
 '4/30/2021',
 '5/01/2021',
 '5/02/2021',
 '5/03/2021',
 '5/04/2021',
 '5/05/2021',
 '5/06/2021',
 '5/07/2021',
 '5/08/2021',
 '5/09/2021',
 '5/10/2021',
 '5/11/2021',
 '5/12/2021',
 '5/13/2021',
 '5/14/2021',
 '5/15/2021',
 '5/16/2021',
 '5/17/2021',
 '5/18/2021',
 '5/19/2021',
 '5/20/2021',
 '5/21/2021',
 '5/22/2021',
 '5/23/2021',
 '5/24/2021',
 '5/25/2021',
 '5/26/2021',
 '5/27/2021',
 '5/28/2021',
 '5/29/2021',
 '5/30/2021',
 '5/31/2021',
 '6/01/2021',
 '6/02/2021',
 '6/03/2021',
 '6/04/2021',
 '6/05/2021',
 '6/06/2021',
 '6/07/2021',
 '6/08/2021',
 '6/09/2021',
 '6/10/2021',
 '6/11/2021',
 '6/12/2021',
 '6/13/2021',
 '6/14/2021',
 '6/15/2021',
 '6/16/2021',
 '6/17/2021',
 '6/18/2021',
 '6/19/2021',
 '6/20/2021',
 '6/21/2021',
 '6/22/2021',
 '6/23/2021',
 '6/24/2021',
 '6/25/2021',
 '6/26/2021',
 '6/27/2021',
 '6/28/2021',
 '6/29/2021',
 '6/30/2021',
 '7/01/2021',
 '7/02/2021',
 '7/03/2021',
 '7/04/2021',
 '7/05/2021',
 '7/06/2021',
 '7/07/2021',
 '7/08/2021',
 '7/09/2021',
 '7/10/2021',
 '7/11/2021',
 '7/12/2021',
 '7/13/2021',
 '7/14/2021',
 '7/15/2021',
 '7/16/2021',
 '7/17/2021',
 '7/18/2021',
 '7/19/2021',
 '7/20/2021',
 '7/21/2021',
 '7/22/2021',
 '7/23/2021',
 '7/24/2021',
 '7/25/2021',
 '7/26/2021',
 '7/27/2021',
 '7/28/2021',
 '7/29/2021',
 '7/30/2021',
 '7/31/2021',
 '8/01/2021',
 '8/02/2021',
 '8/03/2021',
 '8/04/2021',
 '8/05/2021',
 '8/06/2021',
 '8/07/2021',
 '8/08/2021',
 '8/09/2021',
 '8/10/2021',
 '8/11/2021',
 '8/12/2021',
 '8/13/2021',
 '8/14/2021',
 '8/15/2021',
 '8/16/2021',
 '8/17/2021',
 '8/18/2021',
 '8/19/2021',
 '8/20/2021',
 '8/21/2021',
 '8/22/2021',
 '8/23/2021',
 '8/24/2021',
 '8/25/2021',
 '8/26/2021',
 '8/27/2021',
 '8/28/2021',
 '8/29/2021',
 '8/30/2021',
 '8/31/2021',
 '9/01/2021',
 '9/02/2021',
 '9/03/2021',
 '9/04/2021',
 '9/05/2021',
 '9/06/2021',
 '9/07/2021',
 '9/08/2021',
 '9/09/2021',
 '9/10/2021',
 '9/11/2021',
 '9/12/2021',
 '9/13/2021',
 '9/14/2021',
 '9/15/2021',
 '9/16/2021',
 '9/17/2021',
 '9/18/2021',
 '9/19/2021',
 '9/20/2021',
 '9/21/2021',
 '9/22/2021',
 '9/23/2021',
 '9/24/2021',
 '9/25/2021',
 '9/26/2021',
 '9/27/2021',
 '9/28/2021',
 '9/29/2021',
 '9/30/2021',
 '10/01/2021',
 '10/02/2021',
 '10/03/2021',
 '10/04/2021',
 '10/05/2021',
 '10/06/2021',
 '10/07/2021',
 '10/08/2021',
 '10/09/2021',
 '10/10/2021',
 '10/11/2021',
 '10/12/2021',
 '10/13/2021',
 '10/14/2021',
 '10/15/2021',
 '10/16/2021',
 '10/17/2021',
 '10/18/2021',
 '10/19/2021',
 '10/20/2021',
 '10/21/2021',
 '10/22/2021',
 '10/23/2021',
 '10/24/2021',
 '10/25/2021',
 '10/26/2021',
 '10/27/2021',
 '10/28/2021',
 '10/29/2021',
 '10/30/2021',
 '10/31/2021',
 '11/01/2021',
 '11/02/2021',
 '11/03/2021',
 '11/04/2021',
 '11/05/2021',
 '11/06/2021',
 '11/07/2021',
 '11/08/2021',
 '11/09/2021',
 '11/10/2021',
 '11/11/2021',
 '11/12/2021',
 '11/13/2021',
 '11/14/2021',
 '11/15/2021',
 '11/16/2021',
 '11/17/2021',
 '11/18/2021',
 '11/19/2021',
 '11/20/2021',
 '11/21/2021',
 '11/22/2021',
 '11/23/2021',
 '11/24/2021',
 '11/25/2021',
 '11/26/2021',
 '11/27/2021',
 '11/28/2021',
 '11/29/2021',
 '11/30/2021',
 '12/01/2021',
 '12/02/2021',
 '12/03/2021',
 '12/04/2021',
 '12/05/2021',
 '12/06/2021',
 '12/07/2021',
 '12/08/2021',
 '12/09/2021',
 '12/10/2021',
 '12/11/2021',
 '12/12/2021',
 '12/13/2021',
 '12/14/2021',
 '12/15/2021',
 '12/16/2021',
 '12/17/2021',
 '12/18/2021',
 '12/19/2021',
 '12/20/2021',
 '12/21/2021',
 '12/22/2021',
 '12/23/2021',
 '12/24/2021',
 '12/25/2021',
 '12/26/2021',
 '12/27/2021',
 '12/28/2021',
 '12/29/2021',
 '12/30/2021',
 '12/31/2021',
 '1/01/2022',
 '1/02/2022',
 '1/03/2022',
 '1/04/2022',
 '1/05/2022',
 '1/06/2022',
 '1/07/2022',
 '1/08/2022',
 '1/09/2022',
 '1/10/2022',
 '1/11/2022',
 '1/12/2022',
 '1/13/2022',
 '1/14/2022',
 '1/15/2022',
 '1/16/2022',
 '1/17/2022',
 '1/18/2022',
 '1/19/2022',
 '1/20/2022',
 '1/21/2022',
 '1/22/2022',
 '1/23/2022',
 '1/24/2022',
 '1/25/2022',
 '1/26/2022',
 '1/27/2022',
 '1/28/2022',
 '1/29/2022',
 '1/30/2022',
 '1/31/2022',
 '2/01/2022',
 '2/02/2022',
 '2/03/2022',
 '2/04/2022',
 '2/05/2022',
 '2/06/2022',
 '2/07/2022',
 '2/08/2022',
 '2/09/2022',
 '2/10/2022',
 '2/11/2022',
 '2/12/2022',
 '2/13/2022',
 '2/14/2022',
 '2/15/2022',
 '2/16/2022',
 '2/17/2022',
 '2/18/2022',
 '2/19/2022',
 '2/20/2022',
 '2/21/2022',
 '2/22/2022',
 '2/23/2022',
 '2/24/2022',
 '2/25/2022',
 '2/26/2022',
 '2/27/2022',
 '2/28/2022',
 '3/01/2022',
 '3/02/2022',
 '3/03/2022',
 '3/04/2022',
 '3/05/2022',
 '3/06/2022',
 '3/07/2022',
 '3/08/2022',
 '3/09/2022',
 '3/10/2022',
 '3/11/2022',
 '3/12/2022',
 '3/13/2022',
 '3/14/2022',
 '3/15/2022',
 '3/16/2022',
 '3/17/2022',
 '3/18/2022',
 '3/19/2022',
 '3/20/2022',
 '3/21/2022',
 '3/22/2022',
 '3/23/2022',
 '3/24/2022',
 '3/25/2022',
 '3/26/2022',
 '3/27/2022',
 '3/28/2022',
 '3/29/2022',
 '3/30/2022',
 '3/31/2022',
 '4/01/2022',
 '4/02/2022',
 '4/03/2022',
 '4/04/2022',
 '4/05/2022',
 '4/06/2022',
 '4/07/2022',
 '4/08/2022',
 '4/09/2022',
 '4/10/2022',
 '4/11/2022',
 '4/12/2022',
 '4/13/2022',
 '4/14/2022',
 '4/15/2022',
 '4/16/2022',
 '4/17/2022',
 '4/18/2022',
 '4/19/2022',
 '4/20/2022',
 '4/21/2022',
 '4/22/2022',
 '4/23/2022',
 '4/24/2022',
 '4/25/2022',
 '4/26/2022',
 '4/27/2022',
 '4/28/2022',
 '4/29/2022',
 '4/30/2022',
 '5/01/2022',
 '5/02/2022',
 '5/03/2022',
 '5/04/2022',
 '5/05/2022',
 '5/06/2022',
 '5/07/2022',
 '5/08/2022',
 '5/09/2022',
 '5/10/2022',
 '5/11/2022',
 '5/12/2022',
 '5/13/2022',
 '5/14/2022',
 '5/15/2022',
 '5/16/2022',
 '5/17/2022',
 '5/18/2022',
 '5/19/2022',
 '5/20/2022',
 '5/21/2022',
 '5/22/2022',
 '5/23/2022',
 '5/24/2022',
 '5/25/2022',
 '5/26/2022',
 '5/27/2022',
 '5/28/2022',
 '5/29/2022',
 '5/30/2022',
 '5/31/2022',
 '6/01/2022',
 '6/02/2022',
 '6/03/2022',
 '6/04/2022',
 '6/05/2022',
 '6/06/2022',
 '6/07/2022',
 '6/08/2022',
 '6/09/2022',
 '6/10/2022',
 '6/11/2022',
 '6/12/2022',
 '6/13/2022',
 '6/14/2022',
 '6/15/2022',
 '6/16/2022',
 '6/17/2022',
 '6/18/2022',
 '6/19/2022',
 '6/20/2022',
 '6/21/2022',
 '6/22/2022',
 '6/23/2022',
 '6/24/2022',
 '6/25/2022',
 '6/26/2022',
 '6/27/2022',
 '6/28/2022',
 '6/29/2022',
 '6/30/2022',
 '7/01/2022',
 '7/02/2022',
 '7/03/2022',
 '7/04/2022',
 '7/05/2022',
 '7/06/2022',
 '7/07/2022',
 '7/08/2022',
 '7/09/2022',
 '7/10/2022',
 '7/11/2022',
 '7/12/2022',
 '7/13/2022',
 '7/14/2022',
 '7/15/2022',
 '7/16/2022',
 '7/17/2022',
 '7/18/2022',
 '7/19/2022',
 '7/20/2022',
 '7/21/2022',
 '7/22/2022',
 '7/23/2022',
 '7/24/2022',
 '7/25/2022',
 '7/26/2022',
 '7/27/2022',
 '7/28/2022',
 '7/29/2022',
 '7/30/2022',
 '7/31/2022',
 '8/01/2022',
 '8/02/2022',
 '8/03/2022',
 '8/04/2022',
 '8/05/2022',
 '8/06/2022',
 '8/07/2022',
 '8/08/2022',
 '8/09/2022',
 '8/10/2022',
 '8/11/2022',
 '8/12/2022',
 '8/13/2022',
 '8/14/2022',
 '8/15/2022',
 '8/16/2022',
 '8/17/2022',
 '8/18/2022',
 '8/19/2022',
 '8/20/2022',
 '8/21/2022',
 '8/22/2022',
 '8/23/2022',
 '8/24/2022',
 '8/25/2022',
 '8/26/2022',
 '8/27/2022',
 '8/28/2022',
 '8/29/2022',
 '8/30/2022',
 '8/31/2022',
 '9/01/2022',
 '9/02/2022',
 '9/03/2022',
 '9/04/2022',
 '9/05/2022',
 '9/06/2022',
 '9/07/2022',
 '9/08/2022',
 '9/09/2022',
 '9/10/2022',
 '9/11/2022',
 '9/12/2022',
 '9/13/2022',
 '9/14/2022',
 '9/15/2022',
 '9/16/2022',
 '9/17/2022',
 '9/18/2022',
 '9/19/2022',
 '9/20/2022',
 '9/21/2022',
 '9/22/2022',
 '9/23/2022',
 '9/24/2022',
 '9/25/2022',
 '9/26/2022',
 '9/27/2022',
 '9/28/2022',
 '9/29/2022',
 '9/30/2022',
 '10/01/2022',
 '10/02/2022',
 '10/03/2022',
 '10/04/2022',
 '10/05/2022',
 '10/06/2022',
 '10/07/2022',
 '10/08/2022',
 '10/09/2022',
 '10/10/2022',
 '10/11/2022',
 '10/12/2022',
 '10/13/2022',
 '10/14/2022',
 '10/15/2022',
 ...]

#### 데이터프레임 컬럼 위치 변경

In [32]:
doc_final_country = doc_final_country[cols]

In [33]:
doc_final_country.head()

,Country_Region,iso2,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,1/28/2020,1/29/2020,...,2/28/2023,3/01/2023,3/02/2023,3/03/2023,3/04/2023,3/05/2023,3/06/2023,3/07/2023,3/08/2023,3/09/2023
0,Afghanistan,https://public.flourish.studio/country-flags/s...,0,0,0,0,0,0,0,0,...,209322,209340,209358,209362,209369,209390,209406,209436,209451,209451
1,Albania,https://public.flourish.studio/country-flags/s...,0,0,0,0,0,0,0,0,...,334391,334408,334408,334427,334427,334427,334427,334427,334443,334457
2,Algeria,https://public.flourish.studio/country-flags/s...,0,0,0,0,0,0,0,0,...,271441,271448,271463,271469,271469,271477,271477,271490,271494,271496
3,Andorra,https://public.flourish.studio/country-flags/s...,0,0,0,0,0,0,0,0,...,47866,47875,47875,47875,47875,47875,47875,47875,47890,47890
4,Angola,https://public.flourish.studio/country-flags/s...,0,0,0,0,0,0,0,0,...,105255,105277,105277,105277,105277,105277,105277,105277,105288,105288

#### 컬럼명 변경

In [34]:
cols[1] = 'Country_Flag'

In [35]:
doc_final_country.columns = cols
doc_final_country.head()

,Country_Region,Country_Flag,1/22/2020,1/23/2020,1/24/2020,1/25/2020,1/26/2020,1/27/2020,1/28/2020,1/29/2020,...,2/28/2023,3/01/2023,3/02/2023,3/03/2023,3/04/2023,3/05/2023,3/06/2023,3/07/2023,3/08/2023,3/09/2023
0,Afghanistan,https://public.flourish.studio/country-flags/s...,0,0,0,0,0,0,0,0,...,209322,209340,209358,209362,209369,209390,209406,209436,209451,209451
1,Albania,https://public.flourish.studio/country-flags/s...,0,0,0,0,0,0,0,0,...,334391,334408,334408,334427,334427,334427,334427,334427,334443,334457
2,Algeria,https://public.flourish.studio/country-flags/s...,0,0,0,0,0,0,0,0,...,271441,271448,271463,271469,271469,271477,271477,271490,271494,271496
3,Andorra,https://public.flourish.studio/country-flags/s...,0,0,0,0,0,0,0,0,...,47866,47875,47875,47875,47875,47875,47875,47875,47890,47890
4,Angola,https://public.flourish.studio/country-flags/s...,0,0,0,0,0,0,0,0,...,105255,105277,105277,105277,105277,105277,105277,105277,105288,105288

### 최종 가공 완료 파일 저장

In [36]:
doc_final_country.to_csv("COVID-19-master/final_covid_data_for_graph.csv")

### 그래프 만들기
- https://app.flourish.studio/ 로그인
- New visualization 선택 -> Bar Chart Race 선택 -> 데이터 수정 (파일 업로드)
- 최종 그래프 예: https://public.flourish.studio/visualisation/17998107/

<div class="alert alert-block" style="border: 2px solid #1976D2;background-color:#E3F2FD;padding:5px;font-size:0.9em;">
본 자료는 저작권법 제25조 2항에 의해 보호를 받습니다. 본 자료를 외부에 공개하지 말아주세요.<br>
본 강의만 잘 정리하면, 데이터 분석과 데이터 과학(머신러닝, 인공지능) 모두 가능합니다!<br>
<b><a href="https://school.fun-coding.org/">잔재미코딩</a> 에서 본 강의 기반 최적화된 로드맵도 확인하실 수 있습니다</b></div>