# with 구문을 사용한 안전한 파일 읽기

In [3]:
with open('greenData/text_data.txt','r',encoding='utf-8-sig') as f:
    content = f.read()
    print(content)

데이터 분석을 위한 첫 걸음
파이썬 기본 파일 입출력 실습입니다.
1. 기초 문법 익히기
2. 라이브러리 활용하기
3. 시각화 진행하기

# 구문이 끝나면 자동으로 f.close()가 실행됨

# 1. 일반 텍스트 파일 쓰기

In [6]:
with open('greenData/new_notes.txt','w',encoding='utf-8-sig') as f:
    f.write('파이썬 데이터 분석 수업 중입니다.\n')
    f.write('오늘은 파일 입출력을 배우고 있어요.')

# 새로운 CSV 파일 만들기(예: 학생명단)

In [7]:
with open('greenData/new_students.csv', 'w', encoding='utf-8-sig') as f:
    f.write('이름,학과,성적\n')
    f.write('강호동,빅데이터과,90\n')
    f.write('유재석,컴퓨터과,100\n')

# 'a' 모드는 Append(추가)의 약자입니다.

In [8]:
with open('greenData/text_data.txt', 'a', encoding='utf-8-sig') as f:
    f.write('\n새로운 실습 내용이 추가되었습니다.')
    f.write('\n마지막 줄에 이 내용이 붙게 됩니다.')

print("데이터 추가가 완료되었습니다.")

데이터 추가가 완료되었습니다.

# CSV 파일에 새로운 데이터 행 추가
# 각 항목은 쉼표(,)로 구분하고, 마지막에 줄바꿈(\n)을 꼭 넣어주세요.

In [9]:
new_student = '이몽룡,데이터과학과,85,90\n'

with open('greenData/students.csv', 'a', encoding='utf-8-sig') as f:
    f.write(new_student)

print("학생 정보가 성공적으로 추가되었습니다.")

학생 정보가 성공적으로 추가되었습니다.

In [10]:
with open('greenData/score_data.csv','w',encoding='utf-8-sig') as f:
    f.write('이름,국어,영어,수학,전공,출석점수\n')
    f.write('김철수,85,90,78,A,10\n')
    f.write('이영희,92,88,95,B,9\n')
    f.write('박민수,70,60,82,A,7\n')
    f.write('최지아,100,95,90,C,10\n')
    f.write('정바다,88,82,77,B,8\n')
    f.write('강산,65,55,60,A,5\n')

In [18]:
# pandas 라이브러리 불러오기
import pandas as pd
# [2] CSV 데이터 불러오기
# 3강에서 배운 encoding='utf-8-sig'를 여기서도 사용합니다.
df = pd.read_csv('greenData/score_data.csv', encoding='utf-8-sig')

# [6] 데이터 정렬하기 (수학 성적 높은 순)
print("\n--- 수학 성적 우수자 순정렬 ---")
sorted_df = df.sort_values(by='수학', ascending=False)
display(sorted_df)

--- 수학 성적 우수자 순정렬 ---

    이름   국어  영어  수학 전공  출석점수
1  이영희   92  88  95  B     9
3  최지아  100  95  90  C    10
2  박민수   70  60  82  A     7
0  김철수   85  90  78  A    10
4  정바다   88  82  77  B     8
5   강산   65  55  60  A     5

In [19]:
# [조건 1] 수학 점수가 80점 이상인 학생만 필터링
high_math = df[df['수학'] >= 80]
print("--- 수학 80점 이상 학생 ---")
display(high_math)

--- 수학 80점 이상 학생 ---

    이름   국어  영어  수학 전공  출석점수
1  이영희   92  88  95  B     9
2  박민수   70  60  82  A     7
3  최지아  100  95  90  C    10

In [20]:
# [조건 2] 국어 점수가 90점 이상이면서 전공이 'B'인 학생 (다중 조건)
condition = (df['국어'] >= 90) & (df['전공'] == 'B')
target_students = df[condition]
print("\n--- 국어 90점 이상 & 전공 B 학생 ---")
display(target_students)

--- 국어 90점 이상 & 전공 B 학생 ---

    이름  국어  영어  수학 전공  출석점수
1  이영희  92  88  95  B     9

In [21]:
# [열 선택] 이름과 전공 열만 따로 보기
name_major = df[['이름', '전공']]
display(name_major.head())

# [열 추가] 국어, 영어, 수학을 합친 '총점' 열 만들기
df['총점'] = df['국어'] + df['영어'] + df['수학']

# [열 추가] 총점을 3으로 나눈 '평균' 열 만들기
df['평균'] = df['총점'] / 3

print("\n--- 총점과 평균이 추가된 데이터 ---")
display(df)

    이름 전공
0  김철수  A
1  이영희  B
2  박민수  A
3  최지아  C
4  정바다  B

--- 총점과 평균이 추가된 데이터 ---

    이름   국어  영어  수학 전공  출석점수   총점         평균
0  김철수   85  90  78  A    10  253  84.333333
1  이영희   92  88  95  B     9  275  91.666667
2  박민수   70  60  82  A     7  212  70.666667
3  최지아  100  95  90  C    10  285  95.000000
4  정바다   88  82  77  B     8  247  82.333333
5   강산   65  55  60  A     5  180  60.000000

In [22]:
# [그룹화] 전공별로 국어, 영어, 수학의 '평균' 계산하기
# numeric_only=True는 숫자형 데이터만 계산하겠다는 옵션입니다.
major_mean = df.groupby('전공')[['국어', '영어', '수학']].mean()

print("\n--- 전공별 과목 평균 점수 ---")
display(major_mean)

# [응용] 전공별 학생 수 세기
major_count = df.groupby('전공')['이름'].count()
print("\n--- 전공별 학생 인원수 ---")
print(major_count)

--- 전공별 과목 평균 점수 ---

            국어         영어         수학
전공
A    73.333333  68.333333  73.333333
B    90.000000  85.000000  86.000000
C   100.000000  95.000000  90.000000

--- 전공별 학생 인원수 ---
전공
A    3
B    2
C    1
Name: 이름, dtype: int64